// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   avm-transpiler/src/procedures/mod.rs
//   upstream-commit: 233d8e099336c1773b89e939100af047ed9c4f71
//   licence:         MIT-OR-Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-35
// END VENDORED-PROVENANCE

use compiler::{CompiledProcedure, compile};
use msm::MSM_ASSEMBLY;
use parser::parse;

pub(crate) use compiler::scratch_space_range;
pub(crate) use parser::Label;

mod compiler;
mod msm;
mod parser;

#[derive(Debug, Clone, Copy, Eq, PartialEq, Hash)]
pub(crate) enum Procedure {
    MultiScalarMul,
}

pub(crate) fn compile_procedure(procedure: Procedure) -> Result<CompiledProcedure, String> {
    let assembly = match procedure {
        Procedure::MultiScalarMul => MSM_ASSEMBLY,
    };
    let parsed = parse(assembly)?;
    compile(parsed)
}
