// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     avm-corpus
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// The seven AVM corpus programs, with their recorded intent.
//
// ADDED HERE — no upstream counterpart. The programs themselves are upstream-shaped: every
// instruction in them is emitted by upstream's own encoder, and they were originally written
// against upstream's C++ `vm2/testing/BytecodeBuilder` + `InstructionBuilder` in
// `fixtures/wasm-parity/vm2_spike-sources/avm_run.cpp`. This module is the TypeScript
// transcription of those same seven sequences, so that the wire format can be re-derived without a
// barretenberg build — see `avm_corpus_programs.test.ts` for what that buys.
//
// WHY EACH PROGRAM IS HERE is a required field, not a comment. The milestone's deliverable is
// "promoted to a checked-in corpus **with recorded intent**", and a program whose reason for
// existing is not written down cannot later be judged redundant — which is how corpora grow
// without getting stronger. `verify_fixture_corpus_manifest_complete` requires every one of the
// seven to carry an intent.

import { Fr } from '@aztec/foundation/curves/bn254';
import { Point } from '@aztec/foundation/curves/grumpkin';
import { AztecAddress } from '@aztec/stdlib/aztec-address';
import {
  computeContractAddressFromInstance,
  computeContractClassId,
  computePublicBytecodeCommitment,
} from '@aztec/stdlib/contract';
import { PublicKeys } from '@aztec/stdlib/keys';

import { createHash } from 'crypto';

import { TypeTag } from '../public/avm/avm_memory_types.js';
import { Add, Mul } from '../public/avm/opcodes/arithmetic.js';
import { Jump } from '../public/avm/opcodes/control_flow.js';
import { Return, Revert } from '../public/avm/opcodes/external_calls.js';
import { Poseidon2, Sha256Compression } from '../public/avm/opcodes/hashing.js';
import { Set as SetInstr } from '../public/avm/opcodes/memory.js';
import { SStore } from '../public/avm/opcodes/storage.js';
import { Opcode } from '../public/avm/serialization/instruction_serialization.js';

/** No operand in any of the seven is indirect or relative — the C++ builders never call
 * `.indirect()` or `.relative()` for these programs, so the addressing byte is zero throughout. */
const DIRECT = 0;

const set8 = (dst: number, tag: number, value: number | bigint) =>
  new SetInstr(DIRECT, dst, tag, value).as(Opcode.SET_8, SetInstr.wireFormat8);
const set32 = (dst: number, tag: number, value: number | bigint) =>
  new SetInstr(DIRECT, dst, tag, value).as(Opcode.SET_32, SetInstr.wireFormat32);
const setff = (dst: number, value: bigint) =>
  new SetInstr(DIRECT, dst, TypeTag.FIELD, value).as(Opcode.SET_FF, SetInstr.wireFormatFF);
const add8 = (a: number, b: number, dst: number) => new Add(DIRECT, a, b, dst).as(Opcode.ADD_8, Add.wireFormat8);
const mul8 = (a: number, b: number, dst: number) => new Mul(DIRECT, a, b, dst).as(Opcode.MUL_8, Mul.wireFormat8);
const ret = (sizeOffset: number, offset: number) =>
  new Return(DIRECT, sizeOffset, offset).as(Opcode.RETURN, Return.wireFormat);
const revert8 = (sizeOffset: number, offset: number) =>
  new Revert(DIRECT, sizeOffset, offset).as(Opcode.REVERT_8, Revert.wireFormat8);

const bytesOf = (instructions: { toBuffer(): Buffer }[]) => Buffer.concat(instructions.map(i => i.toBuffer()));

export interface CorpusProgram {
  name: string;
  /** Why this program is in the corpus. Required; the manifest check enforces it. */
  intent: string;
  build: () => { toBuffer(): Buffer }[];
}

export const CORPUS_PROGRAMS: CorpusProgram[] = [
  {
    name: 'add',
    intent:
      'The canonical smoke program: ADD two U32s and RETURN. Four instructions. If this one diverges native-versus-wasm then nothing else in the corpus is worth reading, which is exactly what a smoke program is for.',
    build: () => [set8(0, TypeTag.UINT32, 1), set8(1, TypeTag.UINT32, 2), add8(0, 1, 2), ret(0, 2)],
  },
  {
    name: 'revert',
    intent:
      'A deliberate REVERT_8. It exists to exercise the throw/catch revert path, which is the single thing wasi-sdk 27 cannot compile: under barretenberg`s BB_NO_EXCEPTIONS shim (`#define try if(true)`) any C++ exception in a wasm build silently becomes std::abort(), so a revert would look like a crash rather than a revert. This program is the fixture behind M4.',
    build: () => [set8(0, TypeTag.UINT32, 0), revert8(0, 0)],
  },
  {
    name: 'loop',
    intent:
      '64 unrolled iterations of MUL/ADD over U64. Exercises the interpreter over a real instruction count rather than a handful, with tag checking and per-instruction gas accounting on every step, so a gas-table or tag-semantics divergence has somewhere to show up.',
    build: () => {
      const out = [set8(0, TypeTag.UINT32, 0), set8(1, TypeTag.UINT64, 1), set8(2, TypeTag.UINT64, 3)];
      for (let i = 0; i < 64; i++) {
        out.push(mul8(1, 2, 1), add8(1, 2, 1));
      }
      out.push(ret(0, 1));
      return out;
    },
  },
  {
    name: 'sha256',
    intent:
      'SHA256COMPRESSION over 8 state words and 16 input words. Pulls a real crypto gadget into the executed path: a gadget that miscompiles for wasm32 (32-bit shifts, endianness, unaligned loads) is completely invisible to arithmetic-only programs, and this is the cheapest program that would catch it.',
    build: () => {
      const out = [set8(0, TypeTag.UINT32, 0)];
      for (let i = 0; i < 8; i++) {
        out.push(set32(10 + i, TypeTag.UINT32, (0x6a09e667 + i) >>> 0));
      }
      for (let i = 0; i < 16; i++) {
        out.push(set32(26 + i, TypeTag.UINT32, (0x01020304 * (i + 1)) >>> 0));
      }
      out.push(new Sha256Compression(DIRECT, 200, 10, 26).as(Opcode.SHA256COMPRESSION, Sha256Compression.wireFormat));
      out.push(set8(1, TypeTag.UINT32, 8));
      out.push(ret(1, 200));
      return out;
    },
  },
  {
    name: 'poseidon2',
    intent:
      'POSEIDON2PERM — the hash the protocol itself is built on, and the one every merkle domain separator feeds. A divergence in this permutation is a divergence in every tree root in the system, so it is the highest-value single gadget in the seven.',
    build: () => {
      const out = [set8(0, TypeTag.UINT32, 0)];
      for (let i = 0; i < 4; i++) {
        out.push(setff(10 + i, BigInt(i + 1)));
      }
      out.push(new Poseidon2(DIRECT, 10, 20).as(Opcode.POSEIDON2, Poseidon2.wireFormat));
      out.push(set8(1, TypeTag.UINT32, 4));
      out.push(ret(1, 20));
      return out;
    },
  },
  {
    name: 'storage',
    intent:
      'SSTORE of a field to a slot, then a return. The only one of the seven that reaches the merkle DB and moves the public-data tree, which is why its end-public-data root differs from every other program in the native-versus-wasm transcript. Without it the tree-root lines in that transcript would be seven copies of the same constant.',
    build: () => [
      set8(0, TypeTag.UINT32, 0),
      setff(1, 7n),
      setff(2, 1234n),
      new SStore(DIRECT, 2, 1).as(Opcode.SSTORE, SStore.wireFormat),
      set8(4, TypeTag.UINT32, 1),
      ret(4, 2),
    ],
  },
  {
    name: 'burn',
    intent:
      'A tight 16-instruction ADD body with a backward JUMP_32, running until it exhausts the gas limit — 38,903 instructions executed. Two jobs: it gives instructions-per-second on identical work for native versus wasm, and it is the only one of the seven whose halt is out-of-gas rather than RETURN or REVERT, so the out-of-gas path is covered by the transcript at all.',
    build: () => {
      const prologue = [set8(0, TypeTag.UINT64, 1), set8(1, TypeTag.UINT64, 1)];
      const loopStart = bytesOf(prologue).length;
      const body = [];
      for (let i = 0; i < 16; i++) {
        body.push(add8(0, 1, 0));
      }
      return [...prologue, ...body, new Jump(loopStart).as(Opcode.JUMP_32, Jump.wireFormat)];
    },
  },
];

/**
 * The grumpkin generator, which is what `PublicTxSimulationTester::deploy_contract` puts in
 * `PublicKeys{ .incoming_viewing_key = AffinePoint::one(), … }`.
 *
 * `grumpkin::G1Params::one_x` is `fr::one()`, so x = 1; y is the corresponding curve point's
 * ordinate. `Point.YFromX` returns one of the two square roots and grumpkin's `one_y` is the other,
 * so it is negated. That is not a guess dressed up as a fact: with the un-negated root the derived
 * address for `add` is 0x2d212c24…, with the negated one it is 0x2a81495e…, and 0x2a81495e… is
 * what upstream's C++ actually printed (`fixtures/wasm-parity/native-with-roots.results`). The
 * `Point` constructor rejects points that are not on the curve, so the shape is checked too.
 */
async function grumpkinGenerator(): Promise<Point> {
  const y = await Point.YFromX(Fr.ONE);
  if (y === undefined) {
    throw new Error('avm_corpus_programs: no y for grumpkin x = 1');
  }
  return new Point(Fr.ONE, y.negate(), false);
}

/**
 * `PublicTxSimulationTester::deploy_contract`, reproduced field for field: artifact hash 0,
 * private-functions root 0, salt 0, deployer = AztecAddress(100) (`default_sender()`),
 * initialization hash 0, immutables hash 0, and the public keys above.
 */
export async function deriveDeployedAddress(bytecode: Buffer) {
  const bytecodeCommitment = await computePublicBytecodeCommitment(bytecode);
  const contractClassId = await computeContractClassId({
    artifactHash: Fr.ZERO,
    privateFunctionsRoot: Fr.ZERO,
    publicBytecodeCommitment: bytecodeCommitment,
  });
  const address = await computeContractAddressFromInstance({
    version: 1,
    salt: Fr.ZERO,
    deployer: await AztecAddress.fromBigInt(100n),
    currentContractClassId: contractClassId,
    originalContractClassId: contractClassId,
    initializationHash: Fr.ZERO,
    immutablesHash: Fr.ZERO,
    publicKeys: new PublicKeys(Fr.ZERO, await grumpkinGenerator(), Fr.ZERO, Fr.ZERO, Fr.ZERO, Fr.ZERO),
  } as any);
  return { bytecodeCommitment, contractClassId, address };
}

export interface AssembledProgram {
  intent: string;
  instructionCount: number;
  bytes: number;
  sha256: string;
  bytecodeCommitment: string;
  contractClassId: string;
  address: string;
}

/** Assemble all seven and derive everything the transcript records. */
export async function assembleCorpus(): Promise<Record<string, AssembledProgram>> {
  const out: Record<string, AssembledProgram> = {};
  for (const program of CORPUS_PROGRAMS) {
    const instructions = program.build();
    const bytecode = bytesOf(instructions);
    const derived = await deriveDeployedAddress(bytecode);
    out[program.name] = {
      intent: program.intent,
      instructionCount: instructions.length,
      bytes: bytecode.length,
      sha256: createHash('sha256').update(bytecode).digest('hex'),
      bytecodeCommitment: derived.bytecodeCommitment.toString(),
      contractClassId: derived.contractClassId.toString(),
      address: derived.address.toString(),
    };
  }
  return out;
}
