// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     avm-corpus
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart.
//
// `test_seven_avm_programs_assemble` (M2). Each of the seven corpus programs must assemble to the
// byte length and the derived contract address that UPSTREAM's own C++ `BytecodeBuilder` produced.
//
// WHERE THE EXPECTED VALUES COME FROM, which is the whole point. They are not written here. They
// are parsed out of `fixtures/wasm-parity/native-with-roots.results`, the checked-in transcript of
// `avm_spike_runner` — a program built from `vm2/testing/{bytecode_builder,instruction_builder}`
// and run natively. Its `-- program NAME bytes=N` and `address 0x…` lines are what upstream's
// encoder actually emitted.
//
// This test re-assembles the same seven instruction sequences with upstream's TYPESCRIPT encoder
// (the per-opcode `wireFormat` tables plus `serializeAs`) and re-derives the address with
// upstream's `computePublicBytecodeCommitment` / `computeContractClassId` /
// `computeContractAddressFromInstance`. The address is a hash over the entire bytecode, so
// agreement on it is agreement on every byte — which is why this is a genuine cross-implementation
// check on the AVM wire format and needs no barretenberg build.
//
// A byte-length check alone would be much weaker: two encoders can produce the same length and
// different bytes. The address is what closes that.
//
// Regenerate the checked-in summary with:
//   cd diffsim && RUN_AVM_CORPUS=1 UPDATE_AVM_PROGRAM_FIXTURE=1 npm test -- src/corpus

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';

import { CORPUS_PROGRAMS, assembleCorpus } from './avm_corpus_programs.js';

/**
 * Walk up from this test file to the repository root. Derived from the test's own path rather than
 * from `process.cwd()` so the test does not depend on where jest was invoked from, and it throws
 * rather than silently comparing against nothing if the fixtures are not there.
 */
function repoRoot(): string {
  let dir = dirname(String((expect as any).getState().testPath));
  for (let i = 0; i < 12; i++) {
    if (existsSync(resolve(dir, 'fixtures/wasm-parity/native-with-roots.results'))) {
      return dir;
    }
    const up = dirname(dir);
    if (up === dir) {
      break;
    }
    dir = up;
  }
  throw new Error('avm_corpus_programs.test.ts: could not locate the repository root from the test path');
}

const REPO_ROOT = repoRoot();
const TRANSCRIPT = resolve(REPO_ROOT, 'fixtures/wasm-parity/native-with-roots.results');
const WASM_TRANSCRIPT = resolve(REPO_ROOT, 'fixtures/wasm-parity/wasm-with-roots.results');
const FIXTURE = resolve(REPO_ROOT, 'fixtures/avm-programs/programs.json');

/** Parse `-- program NAME bytes=N` / `address 0x…` pairs out of an avm_spike_runner transcript. */
function parseTranscript(path: string): Record<string, { bytes: number; address: string }> {
  const text = readFileSync(path, 'utf8');
  const out: Record<string, { bytes: number; address: string }> = {};
  const lines = text.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const m = /^-- program (\S+) bytes=(\d+)$/.exec(lines[i].trim());
    if (!m) {
      continue;
    }
    const a = /^address\s+(0x[0-9a-f]{64})$/.exec(lines[i + 1].trim());
    if (!a) {
      throw new Error(`transcript ${path}: no address line after "${lines[i]}"`);
    }
    out[m[1]] = { bytes: Number(m[2]), address: a[1] };
  }
  return out;
}

describe('test_seven_avm_programs_assemble', () => {
  it('test_seven_avm_programs_assemble', async () => {
    // The transcripts are checked-in artefacts of upstream's C++ builders. If they are missing the
    // test FAILS — it does not skip and it does not fall back to comparing itself.
    expect(existsSync(TRANSCRIPT)).toBe(true);
    expect(existsSync(WASM_TRANSCRIPT)).toBe(true);

    const native = parseTranscript(TRANSCRIPT);
    const wasm = parseTranscript(WASM_TRANSCRIPT);

    // Exactly seven, named, in the corpus and in the transcript alike.
    const expectedNames = ['add', 'revert', 'loop', 'sha256', 'poseidon2', 'storage', 'burn'];
    expect(CORPUS_PROGRAMS.map(p => p.name)).toEqual(expectedNames);
    expect(Object.keys(native).sort()).toEqual([...expectedNames].sort());
    expect(Object.keys(wasm).sort()).toEqual([...expectedNames].sort());

    const assembled = await assembleCorpus();

    for (const name of expectedNames) {
      // (1) The TypeScript encoder produced the same number of bytes as the C++ BytecodeBuilder.
      expect(assembled[name].bytes).toBe(native[name].bytes);
      // (2) …and the same bytes, proved by the address, which commits to all of them.
      expect(assembled[name].address).toBe(native[name].address);
      // (3) The native and wasm builds of the C++ side agree with each other too, so the recorded
      //     value is not an artefact of one build.
      expect(wasm[name]).toEqual(native[name]);
      // (4) Every program carries a recorded intent. A corpus entry with no stated reason to exist
      //     cannot later be judged redundant, and that is how corpora grow without getting better.
      expect(assembled[name].intent.length).toBeGreaterThan(80);
      // (5) The bytecode is not empty and not a constant.
      expect(assembled[name].bytes).toBeGreaterThan(0);
    }

    // The seven must be genuinely distinct: seven distinct bytecodes, seven distinct addresses.
    // Without this the four assertions above would still pass for seven copies of one program.
    expect(new Set(expectedNames.map(n => assembled[n].sha256)).size).toBe(7);
    expect(new Set(expectedNames.map(n => assembled[n].address)).size).toBe(7);

    const summary = {
      note:
        'Generated by diffsim/src/corpus/avm_corpus_programs.test.ts. `bytes` and `address` are ' +
        "asserted equal to upstream's C++ BytecodeBuilder output as recorded in " +
        'fixtures/wasm-parity/native-with-roots.results.',
      programs: assembled,
    };
    if (process.env.UPDATE_AVM_PROGRAM_FIXTURE) {
      mkdirSync(dirname(FIXTURE), { recursive: true });
      writeFileSync(FIXTURE, JSON.stringify(summary, null, 2) + '\n');
    } else {
      expect(existsSync(FIXTURE)).toBe(true);
      expect(JSON.parse(readFileSync(FIXTURE, 'utf8'))).toEqual(summary);
    }
  });
});
