// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/avm/apps_tests/token.test.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

import { Fr } from '@aztec/foundation/curves/bn254';
import { TokenContractArtifact } from '@aztec/noir-contracts.js/Token';
import { AztecAddress } from '@aztec/stdlib/aztec-address';
import type { ContractInstanceWithAddress } from '@aztec/stdlib/contract';
import { NativeWorldStateService } from '@aztec/world-state';

import { AvmSimulationTester } from '../fixtures/avm_simulation_tester.js';

describe('AVM simulator apps tests: TokenContract', () => {
  const admin = AztecAddress.fromNumber(42);
  const sender = AztecAddress.fromNumber(111);
  const receiver = AztecAddress.fromNumber(222);

  let token: ContractInstanceWithAddress;
  let worldStateService: NativeWorldStateService;
  let simTester: AvmSimulationTester;

  beforeEach(async () => {
    worldStateService = await NativeWorldStateService.tmp();
    simTester = await AvmSimulationTester.create(worldStateService);
    const constructorArgs = [admin, /*name=*/ 'Token', /*symbol=*/ 'TOK', /*decimals=*/ new Fr(18)];
    token = await simTester.registerAndDeployContract(constructorArgs, /*deployer=*/ admin, TokenContractArtifact);

    const constructorResult = await simTester.simulateCall(
      /*sender=*/ admin,
      token.address,
      'constructor',
      constructorArgs,
    );
    expect(constructorResult.reverted).toBe(false);
  });

  afterEach(async () => {
    await worldStateService.close();
  });

  it('token mint, transfer, burn (and check balances)', async () => {
    const mintAmount = 100n;
    const transferAmount = 50n;
    const authwitNonce = new Fr(0);

    await checkBalance(sender, 0n);

    const mintResult = await simTester.simulateCall(
      /*sender=*/ admin,
      token.address,
      'mint_to_public',
      /*args=*/ [/*to=*/ sender, mintAmount],
    );
    expect(mintResult.reverted).toBe(false);
    await checkBalance(sender, mintAmount);

    const transferResult = await simTester.simulateCall(
      /*sender=*/ sender,
      token.address,
      'transfer_in_public',
      /*args=*/ [/*from=*/ sender, /*to=*/ receiver, transferAmount, authwitNonce],
    );
    expect(transferResult.reverted).toBe(false);
    await checkBalance(sender, mintAmount - transferAmount);
    await checkBalance(receiver, transferAmount);

    const burnResult = await simTester.simulateCall(
      /*sender=*/ receiver,
      token.address,
      'burn_public',
      /*args=*/ [/*from=*/ receiver, transferAmount, authwitNonce],
    );
    expect(burnResult.reverted).toBe(false);
    await checkBalance(receiver, 0n);
  });

  const checkBalance = async (account: AztecAddress, expectedBalance: bigint) => {
    const balResult = await simTester.simulateCall(
      sender,
      token.address,
      'balance_of_public',
      /*args=*/ [/*owner=*/ account],
      /*isStaticCall=*/ true,
    );
    expect(balResult.reverted).toBe(false);
    expect(balResult.output.readAll()).toEqual([new Fr(expectedBalance)]);
  };
});
