// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/utils.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

import { PublicCallRequestWithCalldata, type Tx, TxExecutionPhase } from '@aztec/stdlib/tx';

export function getCallRequestsWithCalldataByPhase(tx: Tx, phase: TxExecutionPhase): PublicCallRequestWithCalldata[] {
  switch (phase) {
    case TxExecutionPhase.SETUP:
      return tx.getNonRevertiblePublicCallRequestsWithCalldata();
    case TxExecutionPhase.APP_LOGIC:
      return tx.getRevertiblePublicCallRequestsWithCalldata();
    case TxExecutionPhase.TEARDOWN: {
      const request = tx.getTeardownPublicCallRequestWithCalldata();
      return request ? [request] : [];
    }
    default:
      throw new Error(`Unknown phase: ${phase}`);
  }
}
