import { poseidon2Hash } from '@aztec/foundation/crypto/sync';
import { Fr } from '@aztec/foundation/curves/bn254';
import { NativeWorldStateService } from '@aztec/world-state';
import { MerkleTreeId } from '@aztec/stdlib/trees';
const ws = await NativeWorldStateService.tmp();
const fork = await ws.fork();
const before = new Fr((await fork.getTreeInfo(MerkleTreeId.NOTE_HASH_TREE)).root).toString();
const path0 = (await fork.getSiblingPath(MerkleTreeId.NOTE_HASH_TREE, 0n)).toFields();
const leaf = new Fr(42n);
await fork.appendLeaves(MerkleTreeId.NOTE_HASH_TREE, [leaf]);
const after = new Fr((await fork.getTreeInfo(MerkleTreeId.NOTE_HASH_TREE)).root).toString();
const fold = (l, path) => { let n=l; for (const s of path) n = poseidon2Hash([n, s]); return n.toString(); };
const foldRev = (l, path) => { let n=l; for (const s of path) n = poseidon2Hash([s, n]); return n.toString(); };
console.log('root before      :', before);
console.log('root after       :', after);
console.log('fold(42, path0)  :', fold(leaf, path0));
console.log('foldRev(42,path0):', foldRev(leaf, path0));
console.log('fold(0, path0)   :', fold(Fr.ZERO, path0));
await ws.close();
