#!/usr/bin/env python3
"""Compare upstream's GENERATED IPC schemas against what this repository's wasm
reactor exports actually take, FIELD FOR FIELD, as sets.

WHY THIS FILE EXISTS, because the claim it settles has been repeated without ever
being measured.

`REACTOR-ABI.md` says the host ABI is upstream's own msgpack schemas rather than an
encoding we invented, and `avm_msgpack_coverage` proves that BY EXECUTION for 42
crossed types. Separately, `DRIFT.md` D20 records that upstream moved the AVM and
the world state out of the `@aztec/native` NAPI addon and behind a msgpack IPC
boundary generated by `ipc-codegen` from two schema files. From those two facts the
campaign has been saying that upstream's IPC client and our wasm reactor are "two
transports over one schema".

**That both sides use msgpack IS measured. That the generated schemas are FIELD FOR
FIELD what our exports take was NOT.** This file makes that comparison and reports
whatever it finds. A disagreement is a RESULT to record, not a failure to hide.

WHAT IS COMPARED, AND WHAT A "PAIR" IS

Upstream's schemas are JSON(C) declarations consumed by `ipc-codegen`:

  * `barretenberg/cpp/src/barretenberg/wsdb/wsdb_schema.jsonc`  — the world-state DB
    service, `aztec-wsdb`, the thing that replaced `NativeWorldState`;
  * `barretenberg/cpp/src/barretenberg/avm/avm_schema.json`      — `bb-avm-sim`, the
    thing that replaced `avmSimulate`.

Our side is the C++ the reactor's exports pack and unpack, read out of the SAME
object store at the SAME anchor, by parsing the `SERIALIZATION_FIELDS(...)` and
`MSGPACK_CAMEL_CASE_FIELDS(...)` declarations that decide the wire keys. The two
macros are NOT interchangeable and the difference is the whole point of doing this
by parsing rather than by reading: `SERIALIZATION_FIELDS` emits the C++ member names
verbatim, `MSGPACK_CAMEL_CASE_FIELDS` runs them through `msgpack_detail::camel_case`
first. This file reimplements that transform character for character from
`barretenberg/cpp/src/barretenberg/serialize/msgpack.hpp` and has a unit case for it,
because a comparison that normalised both sides to some third spelling would agree
with itself by construction and answer nothing.

A PAIR is (schema type or command, C++ type), declared by the caller with a reason.
Pairing is a judgement and it is recorded as data so a reviewer can disagree with a
row rather than with a paragraph.

  usage:  _msgpack_schema_compare.py --input <json>   (prints the comparison as JSON)

  input:  {"pairs": [{"id", "schema_kind", "schema_file", "schema_name",
                      "cpp_file", "cpp_type", "why"}, ...],
           "inject": {"<pair id>": "<fabricated field name>"}}

`inject` is the negative control: it plants a field on the SCHEMA side of one pair.
A comparison that cannot see a planted field cannot see a real disagreement either.
Exit status is 0 when every pair agrees, 3 when at least one disagrees, and 2 on a
malformed input — a disagreement and a broken run must not read alike.
"""

from __future__ import annotations

import argparse
import json
import re
import sys

# ---------------------------------------------------------------------------
# upstream's own camelCase transform, transcribed from
# barretenberg/cpp/src/barretenberg/serialize/msgpack.hpp `msgpack_detail::camel_case`.
# An underscore is dropped and, if the NEXT character is a lowercase letter, that
# letter is upper-cased; anything else after an underscore is emitted unchanged and
# clears the flag. `l1_to_l2_message_tree` -> `l1ToL2MessageTree` is the case that
# distinguishes this from a naive title-casing, because `2` is not a lowercase letter.
# ---------------------------------------------------------------------------
def camel_case(name: str) -> str:
    out = []
    to_upper = False
    for c in name:
        if c == "_":
            to_upper = True
            continue
        if to_upper and "a" <= c <= "z":
            out.append(c.upper())
        else:
            out.append(c)
        to_upper = False
    return "".join(out)


def strip_jsonc(text: str) -> str:
    """Remove `//` line comments that are not inside a string literal."""
    out = []
    in_str = False
    esc = False
    i = 0
    while i < len(text):
        c = text[i]
        if in_str:
            out.append(c)
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            out.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < len(text) and text[i + 1] == "/":
            while i < len(text) and text[i] != "\n":
                i += 1
            continue
        out.append(c)
        i += 1
    return "".join(out)


# ---------------------------------------------------------------------------
# C++ side. Find the struct (or `template <...> struct`) with the given name and
# return the field list of whichever of the two macros it declares, plus WHICH macro
# it was — the macro is part of the answer, because it decides the spelling.
#
# The scan is brace-balanced from the struct's opening `{`, so a nested struct's
# macro cannot be attributed to its parent, and it PRINTS what it could not place
# rather than returning an empty list that reads like "no fields".
# ---------------------------------------------------------------------------
MACROS = ("MSGPACK_CAMEL_CASE_FIELDS", "SERIALIZATION_FIELDS")


def cpp_fields(source: str, type_name: str) -> dict:
    pat = re.compile(
        r"(?:template\s*<[^>]*>\s*)?(?:struct|class)\s+" + re.escape(type_name) + r"\b(?!\s*;)"
    )
    m = pat.search(source)
    if not m:
        return {"found": False, "reason": f"no struct/class named {type_name}"}
    brace = source.find("{", m.end())
    if brace < 0:
        return {"found": False, "reason": f"{type_name}: no opening brace"}
    depth = 0
    end = None
    for i in range(brace, len(source)):
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    if end is None:
        return {"found": False, "reason": f"{type_name}: unbalanced braces"}
    body = source[brace : end + 1]

    for macro in MACROS:
        mm = re.search(re.escape(macro) + r"\s*\(", body)
        if not mm:
            continue
        # balanced-paren scan for the argument list
        depth = 0
        start = mm.end() - 1
        stop = None
        for i in range(start, len(body)):
            if body[i] == "(":
                depth += 1
            elif body[i] == ")":
                depth -= 1
                if depth == 0:
                    stop = i
                    break
        if stop is None:
            return {"found": False, "reason": f"{type_name}: unbalanced {macro}(...)"}
        raw = [a.strip() for a in body[start + 1 : stop].split(",")]
        raw = [a for a in raw if a]
        wire = [camel_case(a) if macro == "MSGPACK_CAMEL_CASE_FIELDS" else a for a in raw]
        return {"found": True, "macro": macro, "members": raw, "wire": wire}

    return {
        "found": False,
        "reason": f"{type_name}: declares neither of {', '.join(MACROS)}, so it has no msgpack wire form",
    }


# ---------------------------------------------------------------------------
# Schema side.
# ---------------------------------------------------------------------------
def schema_fields(doc: dict, kind: str, name: str) -> dict:
    """`kind` is `type`, `command.request` or `command.response`."""
    if kind == "type":
        block = doc.get("types", {}).get(name)
        where = f"types.{name}"
    elif kind.startswith("command."):
        half = kind.split(".", 1)[1]
        cmd = doc.get("commands", {}).get(name)
        block = None if cmd is None else cmd.get(half)
        where = f"commands.{name}.{half}"
    elif kind == "error":
        block = doc.get("error")
        where = "error"
    else:
        return {"found": False, "reason": f"unknown schema_kind {kind}"}
    if block is None:
        return {"found": False, "reason": f"{where} is not declared in this schema"}
    return {"found": True, "where": where, "wire": list(block.keys()), "decl": block}


def compare(inp: dict) -> dict:
    schemas: dict[str, dict] = {}
    rows = []
    inject = inp.get("inject", {})

    for pair in inp["pairs"]:
        pid = pair["id"]
        sf = pair["schema_file"]
        if sf not in schemas:
            schemas[sf] = json.loads(strip_jsonc(open(sf).read()))
        s = schema_fields(schemas[sf], pair["schema_kind"], pair["schema_name"])
        c = cpp_fields(open(pair["cpp_file"]).read(), pair["cpp_type"])

        row = {
            "id": pid,
            "why": pair["why"],
            "schema": {"name": pair["schema_name"], "kind": pair["schema_kind"], **s},
            "cpp": {"type": pair["cpp_type"], **c},
        }
        if not s.get("found") or not c.get("found"):
            row["verdict"] = "UNREADABLE"
            row["reason"] = s.get("reason") or c.get("reason")
            rows.append(row)
            continue

        s_wire = list(s["wire"])
        if pid in inject:
            s_wire.append(inject[pid])
            row["injected"] = inject[pid]

        only_schema = sorted(set(s_wire) - set(c["wire"]))
        only_cpp = sorted(set(c["wire"]) - set(s_wire))
        row["only_in_schema"] = only_schema
        row["only_in_cpp"] = only_cpp
        row["shared"] = sorted(set(s_wire) & set(c["wire"]))
        row["order_equal"] = s_wire == c["wire"]
        row["verdict"] = "AGREE" if (not only_schema and not only_cpp) else "DIFFER"
        rows.append(row)

    agree = [r["id"] for r in rows if r["verdict"] == "AGREE"]
    differ = [r["id"] for r in rows if r["verdict"] == "DIFFER"]
    unreadable = [r["id"] for r in rows if r["verdict"] == "UNREADABLE"]
    return {
        "rows": rows,
        "agree": agree,
        "differ": differ,
        "unreadable": unreadable,
        "verdict": "field-for-field" if (not differ and not unreadable) else "not-field-for-field",
    }


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--input", required=True)
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        # The camelCase transform is a thing under test: it is the only reason the two
        # sides can be compared at all, and getting it wrong would make agreements and
        # disagreements alike meaningless. `l1_to_l2_message_tree` is the case a naive
        # implementation gets wrong, because `2` is not a lowercase letter.
        cases = {
            "nullifier": "nullifier",
            "slot": "slot",
            "next_available_leaf_index": "nextAvailableLeafIndex",
            "l1_to_l2_message_tree": "l1ToL2MessageTree",
            "low_leaf_witness_data": "lowLeafWitnessData",
            "is_already_present": "isAlreadyPresent",
        }
        bad = {k: camel_case(k) for k, v in cases.items() if camel_case(k) != v}
        print(json.dumps({"camel_case_cases": len(cases), "wrong": bad}, indent=2))
        return 0 if not bad else 3

    try:
        inp = json.loads(open(args.input).read())
    except Exception as e:  # noqa: BLE001
        print(f"malformed input: {e}", file=sys.stderr)
        return 2
    out = compare(inp)
    print(json.dumps(out, indent=2, sort_keys=True))
    return 0 if out["verdict"] == "field-for-field" else 3


if __name__ == "__main__":
    sys.exit(main())
