#!/usr/bin/env bash
# verify_msgpack_schemas_match_field_for_field
#
# M37 verification: upstream's GENERATED IPC schemas compared against what this
# repository's wasm reactor exports actually take, FIELD FOR FIELD, as sets.
#
# THE CLAIM THIS CHECK EXISTS TO SETTLE, AND WHY IT IS NOT ALREADY SETTLED.
#
# `REACTOR-ABI.md` §"The host ABI is upstream's msgpack schemas" establishes, BY
# EXECUTION, that 42 crossed types round-trip and that 33 of them are declared in
# upstream files no overlay of ours touches. `DRIFT.md` D20 records, separately,
# that upstream moved the AVM and the world state OUT of the `@aztec/native` NAPI
# addon and behind a msgpack IPC boundary whose client, server and types are
# GENERATED by `ipc-codegen` from two schema files.
#
# From those two true statements the campaign has been saying that upstream's IPC
# client and our wasm reactor are "two transports over one schema". **That both
# sides use msgpack, and that our reactor's types are upstream's DECLARED types,
# is measured. That the GENERATED schemas are FIELD FOR FIELD what our exports
# take is NOT** — and M37's own section says in as many words not to promote it by
# repetition. This check makes the comparison and reports whatever it finds. A
# disagreement is a RESULT, recorded, not a failure to hide.
#
# WHAT IT COMPARES
#
#   schema side : barretenberg/cpp/src/barretenberg/wsdb/wsdb_schema.jsonc
#                 barretenberg/cpp/src/barretenberg/avm/avm_schema.json
#                 — both read out of the fork's OBJECT STORE at `anchors.cpp`,
#                   never out of a worktree, so this cannot measure a dirty tree.
#   our side    : the C++ types the reactor's exports pack and unpack, read out of
#                 the SAME object store at the SAME anchor, plus `AvmReactorError`,
#                 which is ours and is extracted from M12's own patch.
#
# The wire keys are decided by two macros that are NOT interchangeable:
# `SERIALIZATION_FIELDS` emits the C++ member names verbatim, and
# `MSGPACK_CAMEL_CASE_FIELDS` runs them through `msgpack_detail::camel_case` first.
# `_msgpack_schema_compare.py` transcribes that transform and its `--self-test`
# exercises it on the case a naive implementation gets wrong
# (`l1_to_l2_message_tree` -> `l1ToL2MessageTree`; `2` is not a lowercase letter).
# Normalising BOTH sides to some third spelling would make the comparison agree
# with itself by construction, which is why it is not done.
#
# THE CONTROLS. Three, because three different things could make this vacuous:
#
#   1. A FABRICATED FIELD planted on the schema side of a pair that AGREES must be
#      reported missing, by name. A comparer that cannot see a planted field cannot
#      see a real one.
#   2. The camelCase transform must be exercised, or every `MSGPACK_CAMEL_CASE_FIELDS`
#      type is compared through an identity function and the two spellings can never
#      be told apart.
#   3. Every pair must be READABLE. An unreadable pair prints `UNREADABLE` and is
#      counted; a comparison over a type the parser could not find would otherwise
#      look like a disagreement, and a comparison over an empty field list would
#      look like an agreement.
#
# Run: just verify-m37-msgpack

TEST_NAME="verify_msgpack_schemas_match_field_for_field"
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
. "$(dirname "${BASH_SOURCE[0]}")/lib_m37.sh"
m37_summary_on_abnormal_exit

command -v python3 >/dev/null 2>&1 || die "python3 is required"
command -v git >/dev/null 2>&1 || die "git is required"
[ -d "$FORK_ROOT/.git" ] || die "the aztec-packages fork is not at $FORK_ROOT"
[ -f "$REPO_ROOT/pins.json" ] || die "pins.json does not exist"

CMP="$VERIFY_DIR/_msgpack_schema_compare.py"
[ -f "$CMP" ] || die "the comparer is missing at $CMP"

M12_PATCH="$VERIFY_DIR/m12/0001-test-vm2-AVM_REACTOR-a-standalone-avm.wasm-reactor-a.patch"
[ -f "$M12_PATCH" ] || die "M12's reactor patch is missing at $M12_PATCH"

ANCHOR="$(python3 -c 'import json;print(json.load(open("'"$REPO_ROOT"'/pins.json"))["anchors"]["cpp"]["commit"])')"
[ -n "$ANCHOR" ] || die "could not read anchors.cpp out of pins.json"

WORK="${M37_MSGPACK_WORK:-$HOME/.cache/aztec-m37-msgpack}"
rm -rf "$WORK"
mkdir -p "$WORK/up" || die "could not create $WORK"

# ---------------------------------------------------------------------------
# §1  The inputs come out of the object store, and the anchor is the pinned one
# ---------------------------------------------------------------------------
printf '\n=== %s\n' "$TEST_NAME"

assert_eq "the anchor this comparison is taken at is pins.json's cpp anchor" \
  "commit" "$(git -C "$FORK_ROOT" cat-file -t "$ANCHOR" 2>/dev/null || echo missing)"
note "anchor: $ANCHOR"

WSDB_REL="barretenberg/cpp/src/barretenberg/wsdb/wsdb_schema.jsonc"
AVM_REL="barretenberg/cpp/src/barretenberg/avm/avm_schema.json"
UP_FILES="$WSDB_REL
$AVM_REL
barretenberg/cpp/src/barretenberg/crypto/merkle_tree/indexed_tree/indexed_leaf.hpp
barretenberg/cpp/src/barretenberg/crypto/merkle_tree/response.hpp
barretenberg/cpp/src/barretenberg/world_state_reference/merkle_tree_id.hpp
barretenberg/cpp/src/barretenberg/vm2/common/aztec_types.hpp
barretenberg/cpp/src/barretenberg/vm2/common/avm_io.hpp
barretenberg/cpp/src/barretenberg/bbapi/bbapi_shared.hpp"

n_up=0
while IFS= read -r rel; do
  [ -n "$rel" ] || continue
  mkdir -p "$WORK/up/$(dirname "$rel")"
  if git -C "$FORK_ROOT" show "$ANCHOR:$rel" > "$WORK/up/$rel" 2>/dev/null; then
    n_up=$((n_up + 1))
  else
    fail "the anchor does not carry $rel"
  fi
done <<EOF
$UP_FILES
EOF
assert_eq "every upstream input was materialised out of the object store" 8 "$n_up"

# `AvmReactorError` is OURS and lives in a file M12's patch ADDS, so it is
# extracted from the patch rather than from the fork. The extraction is asserted
# to have found the declaration, because an empty file would compare as
# UNREADABLE and read like a parser problem rather than like a broken extraction.
OURS="$WORK/avm_msgpack_coverage.cpp"
python3 - "$M12_PATCH" "$OURS" <<'PY'
import sys
patch, out = sys.argv[1], sys.argv[2]
lines = open(patch).read().split("\n")
keep, on = [], False
for ln in lines:
    if ln.startswith("+++ b/"):
        on = ln.endswith("vm2/reactor/avm_msgpack_coverage.cpp")
        continue
    if ln.startswith("--- ") or ln.startswith("diff --git"):
        continue
    if on and ln.startswith("+"):
        keep.append(ln[1:])
open(out, "w").write("\n".join(keep))
PY
assert_file "M12's added coverage translation unit was extracted from the patch" "$OURS"
assert_ge "…and it is not an empty extraction" 200 "$(wc -l < "$OURS" 2>/dev/null || echo 0)"
assert_true "…and it carries the AvmReactorError declaration this repository owns" \
  grep -q 'struct AvmReactorError' "$OURS"

# ---------------------------------------------------------------------------
# §2  The camelCase transform is a thing under test
# ---------------------------------------------------------------------------
SELFTEST="$(python3 "$CMP" --input /dev/null --self-test 2>&1)"
st_rc=$?
assert_eq "the comparer's camelCase self-test exits 0" "0" "$st_rc"
assert_contains "…over a non-empty case list" '"camel_case_cases": 6' "$SELFTEST"
assert_contains "…with nothing wrong" '"wrong": {}' "$SELFTEST"
# The transform must not be an identity, or every camel-cased type is compared
# through a function that changes nothing and the two spellings cannot differ.
assert_eq "…and the transform actually transforms, so it is not an identity" \
  "l1ToL2MessageTree" \
  "$(python3 -c 'import importlib.util,sys
spec=importlib.util.spec_from_file_location("c",sys.argv[1]);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
print(m.camel_case("l1_to_l2_message_tree"))' "$CMP")"

# ---------------------------------------------------------------------------
# §3  The pairs. Each is (schema declaration, C++ type) with a reason.
# ---------------------------------------------------------------------------
U="$WORK/up/barretenberg/cpp/src/barretenberg"
python3 - "$WORK" "$U" "$OURS" <<'PY'
import json, sys
W, U, OURS = sys.argv[1], sys.argv[2], sys.argv[3]
WSDB = f"{U}/wsdb/wsdb_schema.jsonc"
AVM  = f"{U}/avm/avm_schema.json"
IL   = f"{U}/crypto/merkle_tree/indexed_tree/indexed_leaf.hpp"
RS   = f"{U}/crypto/merkle_tree/response.hpp"
MT   = f"{U}/world_state_reference/merkle_tree_id.hpp"
AT   = f"{U}/vm2/common/aztec_types.hpp"
IO   = f"{U}/vm2/common/avm_io.hpp"
BB   = f"{U}/bbapi/bbapi_shared.hpp"

P = lambda **k: k
pairs = [
 P(id="NullifierLeafValue", schema_kind="type", schema_file=WSDB, schema_name="NullifierLeafValue",
   cpp_file=IL, cpp_type="NullifierLeafValue",
   why="wsdb AppendNullifierLeaves and FindNullifierLeafIndices carry it; avm_merkle_db_insert_indexed_leaves_nullifier_tree unpacks exactly this type"),
 P(id="PublicDataLeafValue", schema_kind="type", schema_file=WSDB, schema_name="PublicDataLeafValue",
   cpp_file=IL, cpp_type="PublicDataLeafValue",
   why="wsdb SequentialInsertPublicData carries it; avm_merkle_db_insert_indexed_leaves_public_data_tree unpacks exactly this type"),
 P(id="IndexedNullifierLeafValue", schema_kind="type", schema_file=WSDB, schema_name="IndexedNullifierLeafValue",
   cpp_file=IL, cpp_type="IndexedLeaf",
   why="wsdb GetNullifierLeafPreimage returns it; avm_merkle_db_get_leaf_preimage_nullifier_tree returns IndexedLeaf<NullifierLeafValue>"),
 P(id="IndexedPublicDataLeafValue", schema_kind="type", schema_file=WSDB, schema_name="IndexedPublicDataLeafValue",
   cpp_file=IL, cpp_type="IndexedLeaf",
   why="wsdb GetPublicDataLeafPreimage returns it; avm_merkle_db_get_leaf_preimage_public_data_tree returns IndexedLeaf<PublicDataLeafValue>"),
 P(id="WorldStateRevision", schema_kind="type", schema_file=WSDB, schema_name="WorldStateRevision",
   cpp_file=MT, cpp_type="WorldStateRevision",
   why="every wsdb read command takes one; REACTOR-ABI.md lists WorldStateRevision among the 33 upstream schemas the reactor crosses"),
 P(id="SiblingPathAndIndex", schema_kind="type", schema_file=WSDB, schema_name="SiblingPathAndIndex",
   cpp_file=RS, cpp_type="SiblingPathAndIndex",
   why="wsdb FindSiblingPaths returns it; the same C++ declaration is in the reactor's crossed set"),
 P(id="NullifierLeafUpdateWitnessData", schema_kind="type", schema_file=WSDB, schema_name="NullifierLeafUpdateWitnessData",
   cpp_file=RS, cpp_type="LeafUpdateWitnessData",
   why="wsdb's per-leaf witness record; ours is LeafUpdateWitnessData<NullifierLeafValue>, a member of the SequentialInsertionResult our insert export returns"),
 P(id="PublicDataLeafUpdateWitnessData", schema_kind="type", schema_file=WSDB, schema_name="PublicDataLeafUpdateWitnessData",
   cpp_file=RS, cpp_type="LeafUpdateWitnessData",
   why="the same, for the public data tree"),
 P(id="SequentialInsertionResultNullifier", schema_kind="type", schema_file=WSDB, schema_name="SequentialInsertionResultNullifier",
   cpp_file=RS, cpp_type="SequentialInsertionResult",
   why="wsdb SequentialInsertNullifier's result; avm_merkle_db_insert_indexed_leaves_nullifier_tree returns SequentialInsertionResult<NullifierLeafValue>"),
 P(id="SequentialInsertionResultPublicData", schema_kind="type", schema_file=WSDB, schema_name="SequentialInsertionResultPublicData",
   cpp_file=RS, cpp_type="SequentialInsertionResult",
   why="the same, for the public data tree"),
 P(id="FindLowLeaf.response", schema_kind="command.response", schema_file=WSDB, schema_name="FindLowLeaf",
   cpp_file=RS, cpp_type="GetLowIndexedLeafResponse",
   why="wsdb FindLowLeaf is upstream's IPC spelling of avm_merkle_db_get_low_indexed_leaf, which returns GetLowIndexedLeafResponse"),
 P(id="GetTreeInfo.response", schema_kind="command.response", schema_file=WSDB, schema_name="GetTreeInfo",
   cpp_file=AT, cpp_type="AppendOnlyTreeSnapshot",
   why="wsdb GetTreeInfo is the per-tree read avm_merkle_db_get_archive_snapshot answers with an AppendOnlyTreeSnapshot"),
 P(id="TreeStateReference", schema_kind="type", schema_file=WSDB, schema_name="TreeStateReference",
   cpp_file=AT, cpp_type="TreeSnapshots",
   why="wsdb GetStateReference returns TreeStateReference[]; avm_merkle_db_get_tree_roots returns one TreeSnapshots"),
 P(id="wsdb.error", schema_kind="error", schema_file=WSDB, schema_name="error",
   cpp_file=OURS, cpp_type="AvmReactorError",
   why="the wsdb service's error envelope against the reactor's, which REACTOR-ABI.md says is shaped like upstream's bb::bbapi::ErrorResponse"),
 P(id="avm.error", schema_kind="error", schema_file=AVM, schema_name="error",
   cpp_file=OURS, cpp_type="AvmReactorError",
   why="the bb-avm-sim service's error envelope against the reactor's"),
 P(id="avm.error-vs-bbapi", schema_kind="error", schema_file=AVM, schema_name="error",
   cpp_file=BB, cpp_type="ErrorResponse",
   why="the same schema against UPSTREAM's own envelope, which is the control that the agreement above is about a shape and not about our copy"),
 P(id="Simulate.request", schema_kind="command.request", schema_file=AVM, schema_name="Simulate",
   cpp_file=IO, cpp_type="AvmFastSimulationInputs",
   why="bb-avm-sim Simulate is upstream's IPC spelling of avm_simulate, which takes a msgpack AvmFastSimulationInputs"),
 P(id="SimulateWithHints.request", schema_kind="command.request", schema_file=AVM, schema_name="SimulateWithHints",
   cpp_file=IO, cpp_type="AvmProvingInputs",
   why="bb-avm-sim SimulateWithHints is upstream's IPC spelling of avm_simulate_with_hinted_dbs, which takes a msgpack AvmProvingInputs"),
]
json.dump({"pairs": pairs, "inject": {}}, open(f"{W}/input.json", "w"), indent=1)
# The injected control goes on a pair that AGREES, so the only thing that can
# make it differ is the plant.
inj = dict(json.load(open(f"{W}/input.json")))
inj["inject"] = {"PublicDataLeafValue": "zzzFabricatedFieldThatIsInNoSchema"}
json.dump(inj, open(f"{W}/input-injected.json", "w"), indent=1)
PY
N_PAIRS="$(python3 -c 'import json;print(len(json.load(open("'"$WORK"'/input.json"))["pairs"]))')"
assert_ge "the comparison covers a meaningful number of declared pairs" 15 "$N_PAIRS"

# ---------------------------------------------------------------------------
# §4  The comparison, and its result — whatever it is
# ---------------------------------------------------------------------------
m37_bounded_out "$WORK/out.json" "$WORK/out.err" "$M37_BOUND" python3 "$CMP" --input "$WORK/input.json"
CMP_RC=$?
assert_true "the comparison produced a machine-readable report" test -s "$WORK/out.json"
assert_true "…and the comparer did not fail on a malformed input (that is exit 2)" test "$CMP_RC" -ne 2

read -r N_AGREE N_DIFFER N_UNREAD VERDICT <<EOF
$(python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
print(len(d["agree"]),len(d["differ"]),len(d["unreadable"]),d["verdict"])' "$WORK/out.json")
EOF

assert_eq "every declared pair was readable on both sides" "0" "$N_UNREAD"
assert_eq "…and every pair is accounted for in exactly one bucket" \
  "$N_PAIRS" "$((N_AGREE + N_DIFFER + N_UNREAD))"

# EVERY ROW IS PRINTED, agreements included, and each disagreement PRINTS ITS
# RESIDUE — this campaign's rule for scanners is that they print what they could
# not place rather than reporting a count.
python3 - "$WORK/out.json" <<'PY'
import json, sys
d = json.load(open(sys.argv[1]))
for r in d["rows"]:
    print("  --   {:<10} {}".format(r["verdict"], r["id"]))
    if r["verdict"] == "UNREADABLE":
        print("  --              " + str(r.get("reason")))
        continue
    print("  --              schema: " + str(r["schema"]["wire"]))
    print("  --              cpp   : " + str(r["cpp"]["wire"]) + "  via " + str(r["cpp"]["macro"]))
    if r["verdict"] == "DIFFER":
        print("  --              only in the schema: " + str(r["only_in_schema"]))
        print("  --              only in the C++   : " + str(r["only_in_cpp"]))
PY

# THE MEASURED RESULT. These are pinned as what was measured on 2026-08-30 at the
# `cpp` anchor, per pair by NAME rather than as a total, because a total moving
# from 8/5 to 7/6 would otherwise say nothing about WHICH pair moved. M37's own
# section says a disagreement is a result to record; this is the record.
AGREE_SET="$(python3 -c 'import json,sys;print(" ".join(sorted(json.load(open(sys.argv[1]))["agree"])))' "$WORK/out.json")"
DIFFER_SET="$(python3 -c 'import json,sys;print(" ".join(sorted(json.load(open(sys.argv[1]))["differ"])))' "$WORK/out.json")"

assert_eq "the pairs that agree field for field are exactly these" \
  "IndexedNullifierLeafValue IndexedPublicDataLeafValue NullifierLeafUpdateWitnessData NullifierLeafValue PublicDataLeafUpdateWitnessData PublicDataLeafValue SiblingPathAndIndex WorldStateRevision avm.error avm.error-vs-bbapi wsdb.error" \
  "$AGREE_SET"
assert_eq "…and the pairs that do NOT are exactly these" \
  "FindLowLeaf.response GetTreeInfo.response SequentialInsertionResultNullifier SequentialInsertionResultPublicData Simulate.request SimulateWithHints.request TreeStateReference" \
  "$DIFFER_SET"
assert_eq "so the overall verdict is the one M37 must record" "not-field-for-field" "$VERDICT"
assert_eq "the comparer's exit status agrees with its own verdict" "3" "$CMP_RC"

# The two disagreements that are about a SPELLING and not about a shape, pinned by
# the exact residues, because "they differ" is not a finding and "they differ by
# snake_case versus camelCase in the one type upstream forgot to camel-case" is.
row() { python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
r=[x for x in d["rows"] if x["id"]==sys.argv[2]][0]
print(" ".join(r[sys.argv[3]]))' "$WORK/out.json" "$1" "$2"; }

assert_eq "SequentialInsertionResult: the schema carries the camelCase spelling" \
  "insertionWitnessData lowLeafWitnessData" "$(row SequentialInsertionResultNullifier only_in_schema)"
assert_eq "…while the C++ carries the raw member names, because it uses SERIALIZATION_FIELDS" \
  "insertion_witness_data low_leaf_witness_data" "$(row SequentialInsertionResultNullifier only_in_cpp)"
assert_eq "FindLowLeaf: the schema drops the is_ prefix as well as changing the case" \
  "alreadyPresent" "$(row FindLowLeaf.response only_in_schema)"
assert_eq "…against the C++ member the reactor's export returns" \
  "is_already_present" "$(row FindLowLeaf.response only_in_cpp)"

# And the two that are about a SHAPE. The AVM schema carries the payload as one
# opaque `bytes` field, so it declares NO AVM field at all — which is why the
# "two transports over one schema" sentence is true of the transport and false of
# the declaration.
assert_eq "the bb-avm-sim schema's Simulate request declares exactly one field" \
  "inputs" "$(python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
r=[x for x in d["rows"] if x["id"]=="Simulate.request"][0]
print(" ".join(r["schema"]["wire"]))' "$WORK/out.json")"
assert_eq "…and it is not any field of the type our export actually takes" \
  "inputs" "$(row Simulate.request only_in_schema)"
assert_ge "…while that type has a real field list on our side" 3 \
  "$(python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
r=[x for x in d["rows"] if x["id"]=="Simulate.request"][0]
print(len(r["cpp"]["wire"]))' "$WORK/out.json")"

# ---------------------------------------------------------------------------
# §5  THE NEGATIVE CONTROL: a fabricated field must be reported missing, by name
# ---------------------------------------------------------------------------
m37_bounded_out "$WORK/out-injected.json" "$WORK/out-injected.err" "$M37_BOUND" python3 "$CMP" --input "$WORK/input-injected.json"
INJ_RC=$?
# NOT "the comparer still exits 3". THAT ASSERTION COULD NOT FAIL BECAUSE OF THE PLANT:
# the UNPLANTED run already exits 3, since seven pairs differ without any help, so the
# comparison was true whether or not the plant was ever seen. It caught a crash and
# nothing else, while its description claimed to measure the control. What the plant
# must do is MOVE THE COUNTS — one pair leaves `agree` and joins `differ` — and that is
# false of a comparer that stopped comparing, which is the state the control exists for.
assert_eq "the comparer does not fail on the injected input either (that would be exit 2)" "3" "$INJ_RC"
INJ_AGREE="$(python3 -c 'import json,sys;d=json.load(open(sys.argv[1]));print(len(d["agree"]))' "$WORK/out-injected.json")"
INJ_DIFFER="$(python3 -c 'import json,sys;d=json.load(open(sys.argv[1]));print(len(d["differ"]))' "$WORK/out-injected.json")"
assert_eq "…and the plant moves exactly one pair out of the agreeing set" \
  "$((N_AGREE - 1))" "$INJ_AGREE"
assert_eq "…and into the differing one, so the control is a MEASUREMENT and not an exit code" \
  "$((N_DIFFER + 1))" "$INJ_DIFFER"
INJ_ROW="$(python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
r=[x for x in d["rows"] if x["id"]=="PublicDataLeafValue"][0]
print(r["verdict"], "|", " ".join(r["only_in_schema"]))' "$WORK/out-injected.json")"
assert_eq "…and the pair that AGREED now DIFFERS, naming the planted field" \
  "DIFFER | zzzFabricatedFieldThatIsInNoSchema" "$INJ_ROW"
assert_true "…and PublicDataLeafValue is in the agree set WITHOUT the plant" \
  grep -q '"PublicDataLeafValue"' <(python3 -c 'import json,sys;print(json.dumps(json.load(open(sys.argv[1]))["agree"]))' "$WORK/out.json")

# ---------------------------------------------------------------------------
# §6  What the comparison does NOT establish, asserted so it cannot be forgotten
# ---------------------------------------------------------------------------
# Set equality is not order equality, and msgpack maps are order-insensitive on
# decode but not on ENCODE — `avm_msgpack_coverage` compares re-packed BYTES, so a
# reordering would show there and not here. The two instruments answer different
# questions and this assertion is what says so.
N_ORDER="$(python3 -c '
import json,sys
d=json.load(open(sys.argv[1]))
print(sum(1 for r in d["rows"] if r.get("verdict")=="AGREE" and r.get("order_equal")))' "$WORK/out.json")"
assert_eq "of the agreeing pairs, the field ORDER is identical in every one" \
  "$N_AGREE" "$N_ORDER"

m37_finish
