// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/avm/opcodes/instruction_impl.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

import { OperandType } from '../serialization/instruction_serialization.js';
import { Instruction } from './instruction.js';

/** Wire format that informs deserialization for instructions with three operands. */
export const ThreeOperandWireFormat8 = [
  OperandType.UINT8,
  OperandType.UINT8,
  OperandType.UINT8,
  OperandType.UINT8,
  OperandType.UINT8,
];
export const ThreeOperandWireFormat16 = [
  OperandType.UINT8,
  OperandType.UINT8,
  OperandType.UINT16,
  OperandType.UINT16,
  OperandType.UINT16,
];

/**
 * Covers (de)serialization for an instruction with:
 * addressing mode, inTag, and three operands.
 */
export abstract class ThreeOperandInstruction extends Instruction {
  static readonly wireFormat8: OperandType[] = ThreeOperandWireFormat8;
  static readonly wireFormat16: OperandType[] = ThreeOperandWireFormat16;

  constructor(
    protected addressingMode: number,
    protected aOffset: number,
    protected bOffset: number,
    protected dstOffset: number,
  ) {
    super();
  }
}
