// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/public_errors.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     derived
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

/**
 * Any known (and checked) error that can be thrown during public execution.
 * Includes AvmExecutionErrors and SideEffectErrors.
 *
 * AvmSimulator catches any checked errors before returning a boolean "reverted".
 * Unchecked errors are generally the result of a bug. They are propagated and
 * ultimately will be the resonsibility of PublicProcessor to handle.
 */
export abstract class CheckedPublicExecutionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'CheckedPublicExecutionError';
  }
}
