// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/private/circuit_recording/memory_circuit_recorder.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     derived
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

import type { Logger } from '@aztec/foundation/log';

import { CircuitRecorder } from './circuit_recorder.js';

/**
 * In memory circuit recorder uses the default implementation. This is kept
 * while we decide the fate of the FileCircuitRecorder.
 */
export class MemoryCircuitRecorder extends CircuitRecorder {
  constructor(logger?: Logger) {
    super(logger);
  }
}
