// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   barretenberg/cpp/src/barretenberg/vm2/common/field.hpp
//   upstream-commit: 233d8e099336c1773b89e939100af047ed9c4f71
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-47
// END VENDORED-PROVENANCE

// WARNING: Use this field definition only for simulation and tracegen.
// In the constraints we need to use the Flavor so that it works well with recursion.
#pragma once

#include "barretenberg/vm2/common/standard_affine_point.hpp"
#include "barretenberg/vm2/constraining/flavor_settings.hpp"

namespace bb::avm2 {

using FF = AvmFlavorSettings::FF;
using Fq = AvmFlavorSettings::G1::Fq;
using EmbeddedCurvePoint = StandardAffinePoint<AvmFlavorSettings::EmbeddedCurve::AffineElement>;

} // namespace bb::avm2
