// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   barretenberg/cpp/src/barretenberg/vm2/common/gas.hpp
//   upstream-commit: 233d8e099336c1773b89e939100af047ed9c4f71
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-47
// END VENDORED-PROVENANCE

#pragma once

#include <cstdint>

namespace bb::avm2 {

uint16_t compute_addressing_gas(uint16_t addressing_mode);

} // namespace bb::avm2
