// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   barretenberg/cpp/src/barretenberg/vm2/common/to_radix.hpp
//   upstream-commit: 233d8e099336c1773b89e939100af047ed9c4f71
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-47
// END VENDORED-PROVENANCE

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <vector>

namespace bb::avm2 {

// Radix goes from 0 to 256 (inclusive); entries at indices 0 and 1 are unused.
constexpr size_t NUM_RADIXES = 257;

const std::array<std::vector<uint8_t>, NUM_RADIXES>& get_p_limbs_per_radix();
size_t get_p_limbs_per_radix_size(size_t radix);

} // namespace bb::avm2
