// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   barretenberg/cpp/src/barretenberg/vm2/common/to_radix.test.cpp
//   upstream-commit: 233d8e099336c1773b89e939100af047ed9c4f71
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-47
// END VENDORED-PROVENANCE

#include "barretenberg/vm2/common/to_radix.hpp"

#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include <vector>

namespace bb::avm2 {
namespace {

TEST(ToRadixTest, CheckPlimbsPerRadixSize)
{
    std::vector<size_t> hardcoded_sizes;
    std::vector<size_t> computed_sizes;

    hardcoded_sizes.reserve(NUM_RADIXES);
    computed_sizes.reserve(NUM_RADIXES);

    for (size_t radix = 0; radix < NUM_RADIXES; ++radix) {
        hardcoded_sizes.push_back(get_p_limbs_per_radix_size(radix));
        computed_sizes.push_back(get_p_limbs_per_radix()[radix].size());
    }

    EXPECT_THAT(hardcoded_sizes, ::testing::ElementsAreArray(computed_sizes));
}

} // namespace
} // namespace bb::avm2
