// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart. THE THREE-WAY ARM, over upstream's own corpus drivers.
//
// WHAT IS NEW HERE IS THE ARM, NOT THE CORPUS. Every `it` below drives one of upstream's own
// fixture functions — `tokenTest`, `ammTest`, `bulkTest`, the TWELVE `custom_bytecode_tests` — the
// same functions the two-way suites drive, unedited. That is the point: if the three-way arm ran a
// corpus of its own, agreement between the arms would say nothing about the corpus the campaign
// has been measuring since M2.
//
// THE SUITE NAMES SAY WHAT RUNS. Upstream's `describe.each` rows are labelled `(TS Simulator)` and
// `(Cpp Simulator)`, and both names are wrong about what they select: `useCppSimulator: false`
// selects `CppVsTsPublicTxSimulator`, the DIFFERENTIAL harness, and `useCppSimulator: true`
// selects the C++ AVM alone, which compares nothing. Reading the first label as "the TypeScript
// simulator ran" is what turned 74 comparisons into a reported 756. The rows here are named for
// the configuration in `orchestration/src/simulator_selection.ts` that actually executes.
//
// SEPARATE FAILURE DOMAIN, AND WHAT THAT COSTS. `avm.wasm` is a build output (M6) and this
// repository checks in no binaries, so this arm cannot run in a checkout that has not built one.
// It is therefore gated on `RUN_THREE_WAY` — the same shape upstream uses for `opcode_spam`
// (`RUN_AVM_OPCODE_SPAM`) — so `npm test` and the two-way corpus are untouched by it, in either
// direction. That is M19's containment requirement expressed as a test gate rather than as a wish.
//
// The cost of a gate is that a suite which does not run looks exactly like a suite that passed, and
// this campaign has been bitten by that shape more than once. Two things stop it here. Inside the
// gate, `AVM_WASM_PATH` being unset is ONE FAILING TEST rather than a skip, so a run that gets this
// far and has no module says so. And outside it, `verify_three_way_differential_runs` asserts the
// measured TEST COUNT and the measured TRANSACTION COUNT against
// `fixtures/three-way-arm-counts.json`, so a silently-skipped suite fails the check with the number
// it produced (zero) beside the number it must produce.

import { createLogger } from '@aztec/foundation/log';
import { PublicSimulatorConfig } from '@aztec/stdlib/avm';
import { NativeWorldStateService } from '@aztec/world-state/native';
import { AMMContractArtifact } from '@aztec/noir-contracts.js/AMM';
import { AvmTestContractArtifact } from '@aztec/noir-test-contracts.js/AvmTest';
import { TokenContractArtifact } from '@aztec/noir-contracts.js/Token';

import { ammTest } from '../public/fixtures/amm_test.js';
import { bulkTest } from '../public/fixtures/bulk_test.js';
import * as customBytecode from '../public/fixtures/custom_bytecode_tests.js';
import { defaultGlobals } from '../public/fixtures/public_tx_simulation_tester.js';
import { tokenTest } from '../public/fixtures/token_test.js';
import {
  createThreeWayTester,
  type ThreeWayTester,
} from '../public/public_tx_simulator/differential/three_way_tester.ts';

const CONFIGURATION = 'differential-wasm-vs-native-cpp-vs-typescript';

/**
 * THE PRE-STATE CLAIM, STATED AT THE STRENGTH IT ACTUALLY HOLDS.
 *
 * Every fixture's FIRST transaction runs with all four tree roots and all four leaf counts
 * byte-identical between the two arms — that is what `preStatesProvedIdentical >= 1` asserts here,
 * and it is where "the two arms started from the identical world" is established.
 *
 * It is NOT asserted that every transaction does, and the reason is D15 rather than a weakness in
 * the harness: on 17 of the corpus's 29 transactions the two arms genuinely produce different tree
 * roots, the wasm arm keeps its own, and a later transaction therefore starts from a state that
 * differs by exactly the divergence already reported and attributed. The rule that must hold for
 * every transaction — that NOTHING NEW appears between transactions — is asserted per transaction
 * inside `ThreeWayPublicTxSimulator`, where it can name the trees involved. Writing
 * `toBe(transactionsCompared)` here instead would be a claim the corpus does not support, and it
 * failed exactly that way when it was tried.
 *
 * The measured number is reported rather than hidden: `fixtures/three-way-arm-counts.json` carries
 * it, and `verify_three_way_comparison_count_reported` pins it.
 */
function expectPreStatesIdentical(t: ThreeWayTester): void {
  expect(t.simulator.preStatesProvedIdentical).toBeGreaterThan(0);
}

const config = PublicSimulatorConfig.from({
  skipFeeEnforcement: false,
  collectCallMetadata: true,
  collectDebugLogs: true,
  collectHints: false,
  collectPublicInputs: false,
  collectStatistics: false,
});

/** Set `RUN_THREE_WAY=1`. See the note above on what makes the gate safe. */
const describeOrSkip = process.env.RUN_THREE_WAY ? describe : describe.skip;

describeOrSkip(`AVM three-way differential (${CONFIGURATION})`, () => {
  let ws: NativeWorldStateService;
  let three: ThreeWayTester;

  beforeEach(async () => {
    ws = await NativeWorldStateService.tmp();
    three = await createThreeWayTester(ws, defaultGlobals(), config);
  });

  afterEach(async () => {
    three?.close();
    await ws?.close();
  });

  it('the wasm arm is present', () => {
    // Not a formality. Without this the whole file passes as a two-way differential named
    // three-way, which is the exact overstatement M19 exists to make impossible.
    expect(process.env.AVM_WASM_PATH).toBeTruthy();
    expect(three.resident.treeRoots().nullifierTree.nextAvailableLeafIndex).toBe(128);
  });

  it('TokenContract: constructor, mint, transfer, burn, balances', async () => {
    await tokenTest(three.tester, createLogger('three-way:token'), TokenContractArtifact, (b: boolean) =>
      expect(b).toBe(true),
    );
    expect(three.simulator.transactionsCompared).toBeGreaterThan(0);
    expectPreStatesIdentical(three);
  });

  it('AMM: add liquidity, swap, remove liquidity', async () => {
    await ammTest(
      three.tester,
      createLogger('three-way:amm'),
      TokenContractArtifact,
      AMMContractArtifact,
      (b: boolean) => expect(b).toBe(true),
    );
    expect(three.simulator.transactionsCompared).toBeGreaterThan(0);
    expectPreStatesIdentical(three);
  });

  it('AvmTest bulk_testing', async () => {
    await bulkTest(three.tester, createLogger('three-way:bulk'), AvmTestContractArtifact, (b: boolean) =>
      expect(b).toBe(true),
    );
    expect(three.simulator.transactionsCompared).toBeGreaterThan(0);
  });

  describe('custom bytecode unhappy paths', () => {
    // The TWELVE upstream drivers, enumerated from the module's own exports rather than typed out,
    // so a driver added upstream is picked up rather than missed. Twelve and not eleven: this comment
    // said eleven for one revision, which is the same off-by-one as "the four `cpp_*` files" being
    // five. The floor below is the measured number, so a driver that DISAPPEARS fails here rather
    // than only downstream in the transaction count.
    const drivers = Object.entries(customBytecode).filter(([name]) => name.endsWith('Test'));

    it('enumerates every upstream driver', () => {
      expect(drivers.length).toBeGreaterThanOrEqual(12);
    });

    it.each(drivers.map(([name]) => name))('%s', async (name: string) => {
      const driver = (customBytecode as Record<string, any>)[name];
      // `addressingWithBaseTagIssueTest` takes a leading boolean; the rest take only the tester.
      if (driver.length > 1) {
        await driver(false, three.tester);
      } else {
        await driver(three.tester);
      }
      expect(three.simulator.transactionsCompared).toBeGreaterThan(0);
      expectPreStatesIdentical(three);
    });
  });

  describe('with the AVM circuit public inputs collected', () => {
    // THE BYTE-FOR-BYTE DELIVERABLE, ACTUALLY EXERCISED.
    //
    // Every other suite in this file runs `collectPublicInputs: false`, which is what upstream's
    // apps-tests use — and with it false BOTH C++ arms return `undefined`, so the buffer comparison
    // never fires at all. An assertion that never runs is the campaign's most repeated defect, and
    // the fault-injection controls demonstrated it directly: `M19_INJECT_DIVERGENCE=publicInputs`
    // was GREEN until this block existed, because there was nothing to perturb.
    let ws2: NativeWorldStateService;
    let three2: ThreeWayTester;

    beforeEach(async () => {
      ws2 = await NativeWorldStateService.tmp();
      three2 = await createThreeWayTester(
        ws2,
        defaultGlobals(),
        PublicSimulatorConfig.from({
          skipFeeEnforcement: false,
          collectCallMetadata: true,
          collectDebugLogs: false,
          collectHints: false,
          collectPublicInputs: true,
          collectStatistics: false,
        }),
      );
    });

    afterEach(async () => {
      three2?.close();
      await ws2?.close();
    });

    it('the two arms build the same public-inputs buffer', async () => {
      await customBytecode.invalidOpcodeTest(three2.tester);
      expect(three2.simulator.transactionsCompared).toBeGreaterThan(0);
      expect(three2.simulator.publicInputsBuffersCompared).toBeGreaterThan(0);
    });
  });
});
