// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/public_tx_simulator/apps_tests/avm_test.test.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

import { createLogger } from '@aztec/foundation/log';
import { AvmTestContractArtifact } from '@aztec/noir-test-contracts.js/AvmTest';
import { NativeWorldStateService } from '@aztec/world-state/native';

import { bulkTest } from '../../fixtures/bulk_test.js';
import { PublicTxSimulationTester } from '../../fixtures/public_tx_simulation_tester.js';

describe.each([
  { useCppSimulator: false, simulatorName: 'TS Simulator' },
  { useCppSimulator: true, simulatorName: 'Cpp Simulator' },
])('Public TX simulator apps tests: AvmTestContract ($simulatorName)', ({ useCppSimulator }) => {
  const logger = createLogger('avm-test-contract-tests');

  let worldStateService: NativeWorldStateService;
  let simTester: PublicTxSimulationTester;

  beforeEach(async () => {
    worldStateService = await NativeWorldStateService.tmp();
    simTester = await PublicTxSimulationTester.create(
      worldStateService,
      /*globals=*/ undefined,
      /*metrics=*/ undefined,
      useCppSimulator,
    );
  });

  afterEach(async () => {
    await worldStateService.close();
  });

  it('bulk testing', async () => {
    const result = await bulkTest(simTester, logger, AvmTestContractArtifact);
    expect(result.revertCode.isOK()).toBe(true);
  });
});
