// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/public_tx_simulator/apps_tests/opcode_spam.test.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     oracle-arm
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

import { createLogger } from '@aztec/foundation/log';
import { CollectionLimitsConfig, PublicSimulatorConfig } from '@aztec/stdlib/avm';
import { NativeWorldStateService } from '@aztec/world-state/native';

import { mkdirSync, writeFileSync } from 'fs';
import path from 'path';

import { getSpamConfigsPerOpcode, testOpcodeSpamCase } from '../../fixtures/opcode_spammer.js';
import {
  type MeasuredSimulatorFactory,
  PublicTxSimulationTester,
  defaultGlobals,
} from '../../fixtures/public_tx_simulation_tester.js';
import { SimpleContractDataSource } from '../../fixtures/simple_contract_data_source.js';
import { TestExecutorMetrics } from '../../test_executor_metrics.js';
import { MeasuredCppPublicTxSimulator } from '../cpp_public_tx_simulator.js';
import { MeasuredCppVsTsPublicTxSimulator } from '../cpp_vs_ts_public_tx_simulator.js';

// NOTE: This test is meant to be run for benchmarking. Set RUN_AVM_OPCODE_SPAM=1 to enable.
const describeOrSkip = process.env.RUN_AVM_OPCODE_SPAM ? describe : describe.skip;

/**
 * NOTE: Collecting metadata is technically a slow down, especially
 * for opcodes that do lots of nested calls (like side-effect limited spams).
 * We leave it enabled by default so that we can validate that these
 * tests revert in the expected ways.
 */
// LOCAL DEVIATION FROM UPSTREAM — aztec-avm-runtime, edit class `oracle-arm`. Upstream ships
// `false`. This is M2's decision, taken on measurement rather than preference; the numbers are in
// DRIFT.md D7 and fixtures/differential-arm-counts.json, and the reasoning is:
//
//   With `false`, `collectCallMetadata` is off, so the C++ result carries no call-stack metadata,
//   so `PublicTxResult.findRevertReason()` returns nothing for EVERY halt in this suite, so the
//   differential oracle's exemption fires on 142 of 142 transactions and the arm contributes ZERO
//   revert-reason comparisons. Measured: `revertReasonComparisons: 0, revertReasonExemptions: 142`.
//
//   With `true` the exemption is unreachable here and the arm contributes 142 GENUINE
//   revert-reason comparisons. Measured: `revertReasonComparisons: 142, exemptions: 0`. Since the
//   exemption already fires 0 times in the four metadata-collecting suites, flipping this constant
//   makes our one assertion-relaxing deviation to the oracle DEAD across the entire corpus — the
//   whole 216-transaction differential surface now runs with the revert reason asserted, and
//   `verify_differential_arm_counts_recorded` checks exactly that by requiring the measured
//   exemption count to be zero.
//
//   It also revives two dimensions this arm did not compare at all: `MAX_CALL_STACK_ITEMS` /
//   `_DEPTH` go from 0 to 10000 so call-stack metadata is actually collected and compared, and the
//   app-logic RETURN-VALUE comparison in `cpp_vs_ts_public_tx_simulator.ts` (guarded by
//   `if (this.config?.collectCallMetadata)`) becomes live for all 142. And it makes upstream's own
//   `expectToBeTrue` assertions real rather than the no-op they are while the constant is false.
//
//   Cost, stated rather than buried: ~142 s either way (measured 142.0 s vs 141.6 s, i.e. inside
//   the noise, not the +9 s an earlier estimate predicted), and ONE case — `SENDL2TOL1MSG` — whose
//   halt reason is not in upstream's `allowedReasons` list. That is DRIFT.md D4, a gap in
//   upstream's own fixture rather than a divergence of ours. It is handled below by asserting the
//   known-wrong behaviour EXACTLY, not by skipping it and not by widening upstream's list.
const COLLECT_META_CHECK_RET = true;
const MAX_CALL_STACK_ITEMS = COLLECT_META_CHECK_RET ? 10000 : 0;
const MAX_CALL_STACK_DEPTH = COLLECT_META_CHECK_RET ? 10000 : 0;
const expectToBeTrue = COLLECT_META_CHECK_RET ? (x: boolean) => expect(x).toBe(true) : () => {};

// ---- DRIFT.md D4 ----------------------------------------------------------------------------
// `testSideEffectOpcodeSpam` asserts the inner halt reason is one of
// `['assertion failed', 'out of gas', 'not enough l2gas']`. The SENDL2TOL1MSG spam loop drives the
// recipient past the ETH address bound and halts with an address-bound error that is in none of
// them. Upstream has never seen it because `expectToBeTrue` is a no-op while the constant is
// false, so the assertion is unreachable in a default upstream run.
//
// Three ways to handle it, and why this is the third:
//   (a) skip the case                      — a skipped check is worse than no check;
//   (b) add the error to `allowedReasons`  — that WIDENS an upstream assertion, i.e. weakens it;
//   (c) assert the known-wrong behaviour exactly, so it fails the moment it changes.
// (c) is what is implemented. The case must produce EXACTLY the address-bound reason, upstream's
// list must NOT contain it, and upstream's three assertions must come out exactly
// [pass, FAIL, pass] — reverted, wrong-reason, outer-out-of-gas. If upstream fixes the list, or
// the opcode's error text changes, or the outer frame stops running out of gas, this fails and D4
// has to be re-decided. That is the same discipline DRIFT.md D1 gets.
const D4_CASE_LABEL = 'SENDL2TOL1MSG';
const D4_EXPECTED_INNER_REASON = 'sendl2tol1msg: recipient address is too large';
const D4_UPSTREAM_ALLOWED_REASONS = ['assertion failed', 'out of gas', 'not enough l2gas'];
const D4_EXPECTED_ASSERTION_OUTCOMES = [true, false, true];

describeOrSkip('Opcode Spammer Benchmarks', () => {
  const logger = createLogger('opcode-spam-bench');

  // Get all test cases from the spammer config (grouped by opcode)
  const groupedSpamConfigs = getSpamConfigsPerOpcode();

  // Shared metrics instance for benchmark collection
  const metrics = new TestExecutorMetrics();

  // Benchmark config - disable most collection for speed
  const config: PublicSimulatorConfig = PublicSimulatorConfig.from({
    skipFeeEnforcement: false,
    collectCallMetadata: COLLECT_META_CHECK_RET,
    collectDebugLogs: false,
    collectHints: false,
    collectPublicInputs: false,
    collectStatistics: false,
    // Increase call stack limits for nested call tests (defaults are too low for some opcodes)
    collectionLimits: CollectionLimitsConfig.from({
      maxCallStackItems: MAX_CALL_STACK_ITEMS,
      maxCallStackDepth: MAX_CALL_STACK_DEPTH,
    }),
  });

  afterAll(() => {
    if (process.env.BENCH_OUTPUT) {
      mkdirSync(path.dirname(process.env.BENCH_OUTPUT), { recursive: true });
      writeFileSync(process.env.BENCH_OUTPUT, metrics.toGithubActionBenchmarkJSON());
    } else if (process.env.BENCH_OUTPUT_MD) {
      writeFileSync(process.env.BENCH_OUTPUT_MD, metrics.toPrettyString());
    }
    logger.info(`\n`); // sometimes jest tests obscure the last line(s)
    logger.info(metrics.toPrettyString());
  });

  describe.each([
    // NOTE: Cpp vs TS simulation is very slow (because TS is slow), so we skip it by default.
    // It is useful to manually run to make sure these tests perform identically between simulators.
    // LOCAL DEVIATION FROM UPSTREAM — aztec-avm-runtime, marked SPIKE (fixtures-and-specs).
    // Upstream ships the two arms the other way round (`Cpp` on, `CppVsTs` commented out).
    // We want the differential, which is the whole point of this tree: the `CppVsTs` arm takes
    // the 142 cases from "C++ alone, no comparison" to 142 real TS-vs-C++ comparisons, raising
    // the differential surface from 74 transactions to 216 for ~145 s of wall time. The whole
    // suite stays env-gated behind RUN_AVM_OPCODE_SPAM, so a default run is unaffected.
    // The `Cpp` arm is left off rather than added alongside because it doubles the runtime and
    // produces no comparison; the C++ AVM is still executed, inside the differential.
    // See the deviation note in cpp_vs_ts_public_tx_simulator.ts for the one assertion this
    // needed, and why it is narrower than "skip the revert-reason check".
    { useCppSimulator: false, simulatorName: 'CppVsTs' },
    // { useCppSimulator: true, simulatorName: 'Cpp' },
  ])('($simulatorName) Simulator', ({ useCppSimulator, simulatorName }) => {
    const metricsPrefix = simulatorName;

    let worldStateService: NativeWorldStateService;
    let tester: PublicTxSimulationTester;

    beforeEach(async () => {
      worldStateService = await NativeWorldStateService.tmp();
      const contractDataSource = new SimpleContractDataSource();
      const merkleTree = await worldStateService.fork();
      const simulatorFactory: MeasuredSimulatorFactory = useCppSimulator
        ? (mt, cdb, g, m, c) => new MeasuredCppPublicTxSimulator(mt, cdb, g, m, c)
        : (mt, cdb, g, m, c) => new MeasuredCppVsTsPublicTxSimulator(mt, cdb, g, m, c);
      tester = new PublicTxSimulationTester(
        merkleTree,
        contractDataSource,
        defaultGlobals(),
        metrics,
        simulatorFactory,
        config,
      );
      tester.setMetricsPrefix(`${metricsPrefix} Opcode Spam`);
    });

    afterEach(async () => {
      await worldStateService.close();
    });

    describe.each(groupedSpamConfigs)('$opcode', ({ configs }) => {
      it.each(configs)('$label', async config => {
        if (config.label !== D4_CASE_LABEL) {
          await testOpcodeSpamCase(tester, config, expectToBeTrue);
          return;
        }
        // DRIFT.md D4. Record upstream's assertion outcomes instead of throwing on the first
        // one that is false, then assert the whole pattern. The differential comparison itself
        // still runs in full inside the simulator and is NOT relaxed — this only changes how
        // upstream's own post-hoc expectation is evaluated.
        const outcomes: boolean[] = [];
        const result = await testOpcodeSpamCase(tester, config, (x: boolean) => {
          outcomes.push(x);
        });
        const innerReason = result.findRevertReason()?.message.toLowerCase();
        expect(innerReason).toBe(D4_EXPECTED_INNER_REASON);
        expect(D4_UPSTREAM_ALLOWED_REASONS.some(r => innerReason?.includes(r))).toBe(false);
        expect(outcomes).toEqual(D4_EXPECTED_ASSERTION_OUTCOMES);
      });
    });
  });
});
