// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   avm-transpiler/src/bit_traits.rs
//   upstream-commit: 233d8e099336c1773b89e939100af047ed9c4f71
//   licence:         MIT-OR-Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-35
// END VENDORED-PROVENANCE

use acvm::{AcirField, FieldElement, acir::brillig::MemoryAddress};

fn get_msb(n: u128) -> usize {
    if n == 0 { 0 } else { 128 - n.leading_zeros() as usize }
}

pub trait BitsQueryable {
    fn num_bits(&self) -> usize;
}

impl BitsQueryable for FieldElement {
    fn num_bits(&self) -> usize {
        AcirField::num_bits(self) as usize
    }
}

impl BitsQueryable for u8 {
    fn num_bits(&self) -> usize {
        get_msb(*self as u128)
    }
}

impl BitsQueryable for u16 {
    fn num_bits(&self) -> usize {
        get_msb(*self as u128)
    }
}

impl BitsQueryable for u32 {
    fn num_bits(&self) -> usize {
        get_msb(*self as u128)
    }
}

impl BitsQueryable for u64 {
    fn num_bits(&self) -> usize {
        get_msb(*self as u128)
    }
}

impl BitsQueryable for u128 {
    fn num_bits(&self) -> usize {
        get_msb(*self)
    }
}

impl BitsQueryable for usize {
    fn num_bits(&self) -> usize {
        get_msb(*self as u128)
    }
}

impl BitsQueryable for MemoryAddress {
    fn num_bits(&self) -> usize {
        match self {
            MemoryAddress::Direct(address) => get_msb(*address as u128),
            MemoryAddress::Relative(offset) => get_msb(*offset as u128),
        }
    }
}

pub fn bits_needed_for<T: BitsQueryable>(val: &T) -> usize {
    match val.num_bits() {
        0..=8 => 8,
        9..=16 => 16,
        17..=32 => 32,
        33..=64 => 64,
        65..=128 => 128,
        _ => 254,
    }
}
