// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/public_tx_simulator/apps_tests/cpp_exception_handling.test.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

import { AvmTestContractArtifact } from '@aztec/noir-test-contracts.js/AvmTest';
import { AztecAddress } from '@aztec/stdlib/aztec-address';
import type { ContractInstanceWithAddress } from '@aztec/stdlib/contract';
import { NativeWorldStateService } from '@aztec/world-state/native';

import { PublicTxSimulationTester } from '../../fixtures/public_tx_simulation_tester.js';

describe('C++ Exception Handling during Public Tx Simulation', () => {
  const sender = AztecAddress.fromNumber(42);
  let avmTestContractInstance: ContractInstanceWithAddress;
  let tester: PublicTxSimulationTester;
  let worldStateService: NativeWorldStateService;

  beforeEach(async () => {
    worldStateService = await NativeWorldStateService.tmp();
    tester = await PublicTxSimulationTester.create(
      worldStateService,
      /*globals=*/ undefined,
      /*metrics=*/ undefined,
      /*useCppSimulator=*/ true, // Use C++ simulator
    );
    avmTestContractInstance = await tester.registerAndDeployContract(
      /*constructorArgs=*/ [],
      /*deployer=*/ AztecAddress.fromNumber(420),
      AvmTestContractArtifact,
    );
  });

  afterEach(async () => {
    await worldStateService.close();
  });

  /**
   * Call assertion_failure function during setup, and expect C++ simulator to throw.
   */
  it('assertion failure during setup - C++ simulator should throw and TS should handle gracefully', async () => {
    // expect reject with SimulationError
    await expect(
      tester.simulateTx(
        sender,
        /*setupCalls=*/ [
          {
            address: avmTestContractInstance.address,
            fnName: 'assertion_failure',
            args: [],
          },
        ],
        /*appCalls=*/ [],
      ),
    ).rejects.toThrow(/C\+\+ simulation failed.*SETUP/);
  }, 30_000);
});
