// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     oracle-counters
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED BY aztec-avm-runtime — there is no upstream file at this path.
//
// WHY THIS EXISTS. The differential suite reports a test count. A test count is not a comparison
// count, and in this tree the two have already been confused twice in a way that overstated
// coverage: 756 "differential tests" that were 77, and an `opcode_spam` arm quoted as comparing
// revert reasons on 142 transactions when it compares them on none (DRIFT.md D2, D7). Both were
// found by hand-instrumenting this simulator and throwing the instrumentation away afterwards,
// which means the number had to be re-derived by hand every time anyone wanted it.
//
// So the instrumentation is permanent, off by default, and emits a record per COMPARISON rather
// than per test. `tools/measure_differential.py` turns those records into
// `fixtures/differential-arm-counts.json`, and
// `verification/verify_differential_arm_counts_recorded.sh` re-measures and requires the manifest
// to agree. The headline number therefore cannot drift away from the measured one again without
// a check going red.
//
// COST WHEN OFF. One `process.env` read and an early return per simulated transaction. Nothing is
// allocated, nothing is written, no file descriptor is opened.
//
// WHAT A RECORD MEANS, stated precisely because the whole point is that the number is not
// over-read: a record is written only after every assertion in `CppVsTsPublicTxSimulator.simulate`
// has passed for that transaction. A comparison that FAILS produces no record — the suite is red
// in that case and the measurement is not meaningful anyway. So the counts describe a green run.

import { appendFileSync } from 'fs';
import { join } from 'path';

/** One differential comparison of one transaction. */
export interface DifferentialComparisonRecord {
  /** The jest test file the comparison ran under, relative-ised by the aggregator. */
  file: string;
  /** The jest test name, or '' when it cannot be determined. */
  test: string;
  /**
   * True when the structured revert-reason assertion actually executed for this transaction.
   * False when the metadata-collection exemption fired (DRIFT.md D3/D7) — which is the number
   * that must never be folded into the comparison count.
   */
  revertReasonCompared: boolean;
  /**
   * Which implementation PAIRS were asserted on for this transaction, as
   * `orchestration/src/simulator_selection.ts` names them.
   *
   * ADDED IN M19, and it is the distinction that keeps the headline honest a second time. A
   * transaction is one comparison; a transaction compared by a three-way harness asserts on TWO
   * pairs. Folding the two into one number would inflate the corpus's coverage by counting the
   * same transaction twice, and reporting only the pair count would hide which arms ran. Both are
   * reported, and neither is derivable from the other once some transactions are two-way and some
   * are three-way.
   *
   * Absent in records written before M19; the aggregator defaults those to the two-way pair.
   */
  pairs?: string[];
  /**
   * Whether the two arms' trees were byte-identical before this transaction ran.
   *
   * Absent for the two-way harness, which has one world and therefore no such question to ask.
   * Present and measured for the three-way arm, where the pre-state is held by two different
   * implementations and its identity is the load-bearing claim of the whole arm. Reported as a
   * count, never asserted to be all of them: DRIFT.md D15 is live and carries a divergence forward.
   */
  preStateIdentical?: boolean;
}

/** The pair a two-way `CppVsTsPublicTxSimulator` comparison asserts on. */
export const DEFAULT_PAIR = 'typescript-interpreter:native-cpp-avm';

/**
 * Where the records go. Unset in every normal run, including CI's default `npm test`.
 * The aggregator sets it to a fresh empty directory and reads every `*.jsonl` in it afterwards;
 * jest runs suites in separate worker processes, so the file is per-pid.
 */
const COUNTER_DIR_ENV = 'DIFFSIM_COUNTERS_DIR';

/**
 * Best-effort jest test identity. `expect` is a jest global; outside jest it is absent, and this
 * module must not throw there.
 */
function jestState(): { file: string; test: string } {
  const anyGlobal = globalThis as unknown as {
    expect?: { getState?: () => { testPath?: string; currentTestName?: string } };
  };
  try {
    const state = anyGlobal.expect?.getState?.();
    return { file: state?.testPath ?? '', test: state?.currentTestName ?? '' };
  } catch {
    return { file: '', test: '' };
  }
}

/** Record one completed differential comparison. A no-op unless the sink directory is set. */
export function recordDifferentialComparison(
  revertReasonCompared: boolean,
  pairs: string[] = [DEFAULT_PAIR],
  preStateIdentical?: boolean,
): void {
  const dir = process.env[COUNTER_DIR_ENV];
  if (!dir) {
    return;
  }
  const { file, test } = jestState();
  const record: DifferentialComparisonRecord = { file, test, revertReasonCompared, pairs };
  if (preStateIdentical !== undefined) {
    record.preStateIdentical = preStateIdentical;
  }
  appendFileSync(join(dir, `${process.pid}.jsonl`), JSON.stringify(record) + '\n');
}
