// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/avm/avm_execution_environment.test.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

import { Fr } from '@aztec/foundation/curves/bn254';
import { AztecAddress } from '@aztec/stdlib/aztec-address';

import { CallDataArray } from './calldata.js';
import { initExecutionEnvironment } from './fixtures/initializers.js';
import { allSameExcept } from './fixtures/utils.js';

describe('Execution Environment', () => {
  const newAddress = AztecAddress.fromNumber(123456);
  const calldata = new CallDataArray([new Fr(1n), new Fr(2n), new Fr(3n)]);

  it('New call should fork execution environment correctly', () => {
    const executionEnvironment = initExecutionEnvironment();
    const newExecutionEnvironment = executionEnvironment.deriveEnvironmentForNestedCall(newAddress, calldata);

    expect(newExecutionEnvironment).toEqual(
      allSameExcept(executionEnvironment, {
        address: newAddress,
        contractCallDepth: Fr.ONE,
        calldata: calldata,
      }),
    );
  });

  it('New static call should fork execution environment correctly', () => {
    const executionEnvironment = initExecutionEnvironment();
    const newExecutionEnvironment = executionEnvironment.deriveEnvironmentForNestedStaticCall(newAddress, calldata);

    expect(newExecutionEnvironment).toEqual(
      allSameExcept(executionEnvironment, {
        address: newAddress,
        contractCallDepth: Fr.ONE,
        isStaticCall: true,
        calldata: calldata,
      }),
    );
  });
});
