// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart.
//
// THE DIVERGENCE LEDGER, and the reason it is a ledger rather than an exemption.
//
// M19 measured that the wasm AVM and the NAPI oracle do not agree on metered gas. That is not a
// wasm defect and not a harness defect: the module is built from anchor `cpp` and the oracle is
// the in-process NAPI AVM in `@aztec/native` at pin `npm.deletion_era`, which is anchor `ts` —
// TWO MONTHS and 276 changed `vm2/` files earlier. DD-12 predicted exactly this decay; M19 is
// where it stopped being a prediction.
//
// The campaign has one standing rule about this shape of thing, learned the hard way: an
// assertion-relaxing exemption is the most dangerous artefact you can add, and M2 removed the only
// one this tree had. So the ledger is built to be the opposite of an exemption:
//
//   * It is keyed on (PAIR, FIELD) — not on a test, not on a transaction. A divergence on a field
//     nobody recorded fails the run, wherever it appears.
//   * It is MEASURED. `tools/measure_three_way.py` regenerates it from a survey run; nothing here
//     is hand-written, and the file records the wall-clock and the two pins it was measured under.
//   * It is exact in BOTH directions. An entry that never fires is as much a failure as a
//     divergence that is not entered: a stale entry means the ledger has stopped describing the
//     tree, and a ledger that has stopped describing the tree is how an exemption becomes a hole.
//   * Every entry carries a DRIFT.md id. An entry with no investigation behind it is rejected by
//     the checker, so "it diverges and we do not know why" cannot be written down as if it were an
//     answer.
//
// And the fields NOT in it are the point. `revertCode`, `publicInputs`, `appLogicReturnValues` and
// `revertReason` are what the swap has to preserve; if any of them ever enters this file, that is
// a finding about the AVM and not a housekeeping edit.

import { appendFileSync, existsSync, readFileSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

export interface DivergenceEntry {
  /** The implementation pair, as `simulator_selection.ts` names them. */
  pair: string;
  /** The `COMPARED_FIELDS` name, or `treeRoots`. */
  field: string;
  /** The DRIFT.md entry that explains it. Required. */
  drift: string;
  /** What a reader must not conclude from this entry being here. */
  note: string;
  /**
   * The EXACT disagreements this entry accounts for, as short hashes of their detail text.
   *
   * ADDED after the fault-injection controls found the hole. Keyed on (pair, field) alone, an
   * entry for `gasUsed.totalGas` excused ANY gas disagreement — so
   * `M19_INJECT_DIVERGENCE=totalGas`, which moves the wasm arm's L2 gas by one, went GREEN. Two of
   * the ten controls did. Signatures close that: a recorded divergence is a recorded VALUE, and a
   * different value in the same field is unaccounted and fails.
   *
   * The corpus is deterministic, so the set is stable; `tools/measure_three_way.py` regenerates it.
   */
  signatures?: string[];
}

export interface DivergenceLedger {
  measuredAt: string;
  modulePin: string;
  oraclePin: string;
  entries: DivergenceEntry[];
}

function ledgerPath(): string {
  // Derived from this module's own location, not from `process.cwd()`: jest is invoked from
  // several directories in this repo and a cwd-relative path has already produced a check that
  // compared against nothing.
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, '../../../../../fixtures/differential-wasm-divergences.json');
}

let cached: DivergenceLedger | undefined;

/**
 * The ledger. A MISSING file is an empty ledger — deliberately the strict reading, so that a lost
 * fixture makes every divergence unaccounted rather than making every divergence permitted.
 */
export function divergenceLedger(): DivergenceLedger {
  if (cached === undefined) {
    const path = ledgerPath();
    cached = existsSync(path)
      ? (JSON.parse(readFileSync(path, 'utf8')) as DivergenceLedger)
      : { measuredAt: '', modulePin: '', oraclePin: '', entries: [] };
  }
  return cached;
}

export function isRecordedDivergence(pair: string, field: string, signature: string): boolean {
  const entry = divergenceLedger().entries.find(e => e.pair === pair && e.field === field);
  if (entry === undefined) {
    return false;
  }
  // A ledger written before signatures existed accounts for nothing: an entry with an absent or
  // empty signature list is treated as unaccounted rather than as a wildcard. The strict reading
  // is deliberate — a half-migrated ledger must fail loudly, not permit everything.
  return (entry.signatures ?? []).includes(signature);
}

/**
 * Where a survey run writes what it saw. Unset in a normal run; the aggregator sets it. Same
 * discipline as `differential_counters.ts`: off by default, one `process.env` read per
 * transaction, per-pid file because jest runs suites in separate workers.
 */
const SURVEY_DIR_ENV = 'M19_SURVEY_DIR';

export function surveying(): boolean {
  return Boolean(process.env[SURVEY_DIR_ENV]);
}

export function recordDivergences(
  found: readonly { pair: string; field: string; detail: string; signature?: string }[],
): void {
  const dir = process.env[SURVEY_DIR_ENV];
  if (!dir) {
    return;
  }
  const anyGlobal = globalThis as unknown as {
    expect?: { getState?: () => { testPath?: string; currentTestName?: string } };
  };
  let file = '';
  let test = '';
  try {
    const state = anyGlobal.expect?.getState?.();
    file = state?.testPath ?? '';
    test = state?.currentTestName ?? '';
  } catch {
    /* not under jest */
  }
  const lines = found.length
    ? found.map(d => JSON.stringify({ file, test, ...d }))
    : [JSON.stringify({ file, test, pair: '', field: '', detail: 'agreed on every field', signature: '' })];
  appendFileSync(join(dir, `${process.pid}.jsonl`), lines.join('\n') + '\n');
}
