// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart.
//
// The encoder call, in this package's own dependency resolution, and the reason that qualifier is
// load-bearing rather than pedantic.
//
// WHAT THIS IS NOT. It is not a second encoder. Every line below calls `@aztec/stdlib`:
// `AvmTxHint.fromTx`, `new AvmFastSimulationInputs(...)` and `serializeWithMessagePack`, in
// upstream's own constructor order — exactly what `CppPublicTxSimulator` does, which is why the
// C++ arm and the wasm arm are given bytes produced by the same code. RI-60 records the finding
// that this encoder existed all along.
//
// WHY IT IS NOT IMPORTED FROM `orchestration/src/avm_inputs.ts`, WHICH HAS THE SAME SIX LINES.
// MEASURED, in M19, because the first version of this arm did import it and failed in a way that
// took a shape dump to diagnose:
//
//   `orchestration/` and `diffsim/` each have their own `node_modules`, so each has its own
//   installed copy of `@aztec/foundation` and `@aztec/stdlib`. `serializeWithMessagePack`
//   registers its msgpackr extensions with `addExtension({ Class: Fr, ... })`, and msgpackr
//   dispatches those on CLASS IDENTITY. An `Fr` built by diffsim's copy is not the `Fr` that
//   orchestration's copy registered, so no extension matched and every field element crossed the
//   boundary as a msgpack STRING instead of the 32-byte `bin` the C++ reader expects.
//
//   The module's diagnosis for that is `std::bad_cast` — no field name, no path, no type. The
//   structure was otherwise perfect: same keys, same nesting, same order. Only the leaves moved,
//   and only for the types with a registered extension. So the failure was maximally quiet and
//   maximally misleading; it looks exactly like the schema drift DD-12 predicts and was nothing of
//   the kind.
//
// Hence two things. This module imports `@aztec/stdlib` from the package it runs in, and
// `assertFieldElementsAreBinary` below turns that failure mode into a named assertion BEFORE the
// bytes cross, so the next person gets "chainId encoded as a string, not a 32-byte bin — msgpackr
// extensions are keyed on class identity" instead of `std::bad_cast`.

import {
  AvmFastSimulationInputs,
  AvmTxHint,
  type PublicSimulatorConfig,
  serializeWithMessagePack,
} from '@aztec/stdlib/avm';
import { ProtocolContractsList } from '@aztec/protocol-contracts';
import type { GlobalVariables, Tx } from '@aztec/stdlib/tx';
import { WorldStateRevision } from '@aztec/stdlib/world-state';

import { unpack } from '../../../../../node-host/src/index.ts';

/**
 * The revision that crosses under the RESIDENT shape. Upstream reads a plain `WorldStateRevision`
 * from `merkleTree.getRevision()` and passes an IPC path separately; there is no IPC path here
 * because the world state is inside the module, named by `avm_simulate`'s `merkleDb` argument.
 * The revision is still a field of upstream's input schema, so it is still supplied.
 */
export function residentWorldStateRevision(blockNumber: number): WorldStateRevision {
  return new WorldStateRevision(0, blockNumber, true);
}

/**
 * Field-element paths in the encoded input that MUST be a 32-byte msgpack `bin`.
 *
 * Chosen so that each one is reached through a different extension registration —
 * `config.proverId` is an `Fr`, `globalVariables.chainId` is an `Fr` on a different object,
 * `tx.feePayer` is an `AztecAddress` (whose extension writes an `Fr`, so it exercises both), and
 * `protocolContracts.derivedAddresses[0]` is inside an array. A single path would have gone green
 * on the very failure this exists to catch: in the measured instance
 * `protocolContracts.derivedAddresses` was STILL `bin(32)` while everything else had become a
 * string, so a check that had picked that one path would have passed.
 */
const FIELD_ELEMENT_PATHS: readonly string[] = [
  'config.proverId',
  'globalVariables.chainId',
  'globalVariables.coinbase',
  'tx.feePayer',
  'protocolContracts.derivedAddresses.0',
];

function at(value: unknown, path: string): unknown {
  let cursor: any = value;
  for (const step of path.split('.')) {
    if (cursor === undefined || cursor === null) {
      return undefined;
    }
    cursor = cursor[step];
  }
  return cursor;
}

/**
 * Refuse to cross the boundary with field elements that are not 32-byte binaries.
 *
 * Cheap (one msgpack decode of a ~7 KB blob) and it converts the single quietest failure this arm
 * has into a named one. It re-decodes the bytes actually produced rather than inspecting the
 * objects, because what is under test is the ENCODING, not the input.
 */
export function assertFieldElementsAreBinary(encoded: Uint8Array): void {
  const decoded = unpack(encoded);
  const wrong: string[] = [];
  for (const path of FIELD_ELEMENT_PATHS) {
    const leaf = at(decoded, path);
    if (leaf === undefined) {
      wrong.push(`${path} is absent from the encoded input`);
    } else if (!(leaf instanceof Uint8Array)) {
      wrong.push(`${path} encoded as ${typeof leaf}, not a 32-byte bin`);
    } else if (leaf.length !== 32) {
      wrong.push(`${path} encoded as bin(${leaf.length}), not bin(32)`);
    }
  }
  if (wrong.length > 0) {
    throw new Error(
      'the AVM input encoder did not produce field elements as 32-byte binaries, so the module ' +
        'would fail with std::bad_cast and name nothing: ' +
        wrong.join('; ') +
        '. The usual cause is two installed copies of @aztec/foundation: msgpackr dispatches ' +
        'serializeWithMessagePack\'s extensions on class identity, so an Fr from one copy is not ' +
        'the Fr the other copy registered.',
    );
  }
}

/**
 * FIELDS THE PATCHED MODULE REQUIRES THAT UPSTREAM'S SCHEMA DOES NOT CARRY. DRIFT.md D14.
 *
 * This is not upstream drift and it must not be filed as such. `avm.wasm` is built from the C++
 * anchor PLUS this campaign's own patch stack, and M9's observation-hook patch adds
 * `collect_execution_steps` to `PublicSimulatorConfig` — including to its
 * `MSGPACK_CAMEL_CASE_FIELDS` list, which makes it a REQUIRED field on the wire. bb's msgpack
 * reader refuses a map that lacks it: `Missing field collectExecutionSteps`.
 *
 * The patch is additive in C++ (it has a default, and the field is inert unless set), and the M9
 * checks assert that. It is NOT additive on the wire, and nothing asserted that, because until
 * M19 nothing encoded these inputs from TypeScript — every host read a blob the patched C++ had
 * written, so the encoder and the decoder were the same build and agreed with each other by
 * construction. That is the same shape as D12's fuzzer log codec: an encoder and a decoder that
 * are wrong together and whose round trip therefore always closes.
 *
 * WHAT IS DONE ABOUT IT HERE, and why not something cleaner. The honest fix is to keep the field
 * out of the wire schema and rebuild, which is M9's patch to change and a wasm rebuild to pay for.
 * Until then the wasm arm is handed upstream's bytes PLUS exactly these keys, the delta is
 * COMPUTED from the two encodings rather than asserted from this list, and the comparison refuses
 * to run if the delta is anything other than this. So the claim "both arms received the same
 * transaction" stays true and stays measured, and the exception is one named boolean rather than
 * a shrug.
 */
export const PATCH_REQUIRED_CONFIG_FIELDS: Readonly<Record<string, boolean>> = {
  collectExecutionSteps: false,
};

/**
 * Encode a transaction the way upstream encodes it. The only statement made here is the ORDER,
 * and that is upstream's constructor's. These are the bytes the NATIVE arm receives.
 */
export function encodeFastSimulationInputs(
  tx: Tx,
  globalVariables: GlobalVariables,
  config: PublicSimulatorConfig,
  wsRevision: WorldStateRevision,
): Uint8Array {
  const txHint = AvmTxHint.fromTx(tx, globalVariables.gasFees);
  const inputs = new AvmFastSimulationInputs(wsRevision, config, txHint, globalVariables, ProtocolContractsList);
  const encoded = serializeWithMessagePack(inputs);
  assertFieldElementsAreBinary(encoded);
  return encoded;
}

/**
 * The same inputs, plus the keys the patched module requires. Returned with the upstream encoding
 * beside it so a caller can prove the difference is only those keys.
 */
export function encodeForPatchedModule(
  tx: Tx,
  globalVariables: GlobalVariables,
  config: PublicSimulatorConfig,
  wsRevision: WorldStateRevision,
  /** Extra keys, for the `encoding` fault injection only. Empty in every real run. */
  injectedConfigFields: Record<string, boolean> = {},
): { upstream: Uint8Array; patched: Uint8Array } {
  const upstream = encodeFastSimulationInputs(tx, globalVariables, config, wsRevision);
  const txHint = AvmTxHint.fromTx(tx, globalVariables.gasFees);
  const patchedConfig = { ...config, ...PATCH_REQUIRED_CONFIG_FIELDS, ...injectedConfigFields };
  const inputs = new AvmFastSimulationInputs(
    wsRevision,
    patchedConfig as unknown as PublicSimulatorConfig,
    txHint,
    globalVariables,
    ProtocolContractsList,
  );
  const patched = serializeWithMessagePack(inputs);
  assertFieldElementsAreBinary(patched);
  return { upstream, patched };
}

/**
 * Every difference between two encodings, as `path: a -> b` strings.
 *
 * Deliberately a full recursive walk rather than a check of the keys this file expects to differ:
 * the point is to catch a difference this file did NOT expect. Comparing against the expected list
 * would make the assertion incapable of failing for anything else, which is the campaign's most
 * repeated defect.
 */
export function encodingDifferences(a: Uint8Array, b: Uint8Array): string[] {
  const out: string[] = [];
  walk(unpack(a), unpack(b), '', out);
  return out;
}

function walk(a: unknown, b: unknown, path: string, out: string[]): void {
  const here = path || '<root>';
  if (a instanceof Uint8Array || b instanceof Uint8Array) {
    if (!(a instanceof Uint8Array) || !(b instanceof Uint8Array)) {
      out.push(`${here}: one side is binary and the other is not`);
    } else if (Buffer.compare(Buffer.from(a), Buffer.from(b)) !== 0) {
      out.push(`${here}: binary values differ`);
    }
    return;
  }
  if (Array.isArray(a) || Array.isArray(b)) {
    if (!Array.isArray(a) || !Array.isArray(b)) {
      out.push(`${here}: one side is an array and the other is not`);
      return;
    }
    if (a.length !== b.length) {
      out.push(`${here}: ${a.length} elements vs ${b.length}`);
      return;
    }
    a.forEach((x, i) => walk(x, b[i], `${path}[${i}]`, out));
    return;
  }
  if (a !== null && b !== null && typeof a === 'object' && typeof b === 'object') {
    const ka = Object.keys(a as object);
    const kb = Object.keys(b as object);
    for (const k of ka) {
      if (!kb.includes(k)) {
        out.push(`${path ? path + '.' : ''}${k}: present on the left only`);
      }
    }
    for (const k of kb) {
      if (!ka.includes(k)) {
        out.push(`${path ? path + '.' : ''}${k}: present on the right only`);
      } else {
        walk((a as any)[k], (b as any)[k], `${path ? path + '.' : ''}${k}`, out);
      }
    }
    return;
  }
  if (a !== b) {
    out.push(`${here}: ${String(a)} -> ${String(b)}`);
  }
}

/** The differences `PATCH_REQUIRED_CONFIG_FIELDS` accounts for, in `encodingDifferences`'s spelling. */
export function expectedPatchDifferences(): string[] {
  return Object.keys(PATCH_REQUIRED_CONFIG_FIELDS).map(k => `config.${k}: present on the right only`);
}
