// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart.
//
// THE CONTROLS. A differential that has never been observed to fail is indistinguishable from one
// that cannot, and this campaign has shipped twenty-four assertions that could not fail. So the arm
// carries permanent, named fault injection: `M19_INJECT_DIVERGENCE=<name>` perturbs ONE thing on
// the wasm side just before the comparison, and `e2e_differential_wasm_vs_native_cpp` runs the arm
// once per name and requires it to go RED with at least one failing test. It does not require the
// name to appear in the message, and this sentence said it did for one revision.
//
// Same shape as M8's `verify_avm_differential_exit_status`, which runs its gate eight times over
// five injected divergences, and for the same reason.
//
// ONE INJECTION PER COMPARED FIELD, WHICH IS THE POINT. A conjunction whose only negative case
// exercises one conjunct passes when any of the others is dropped — the campaign shipped exactly
// that as a four-tree conjunction with one control. Here every field in `COMPARED_FIELDS` has its
// own injection, plus one for the pre-state proof, one for the input encoding and one for the
// TypeScript arm's presence, so dropping any single assertion turns exactly one control green and
// is caught. Eleven in all — `INJECTIONS` is the authority and the check enumerates it from this
// file rather than counting on this sentence.
//
// OFF BY DEFAULT AND UNREACHABLE WITHOUT THE VARIABLE. One `process.env` read per transaction and
// an early return; nothing is allocated and no result is copied when it is unset. It lives under
// `differential/` and nothing in the shipped package can reach it.

import { Fr } from '@aztec/foundation/curves/bn254';
import { PublicTxResult } from '@aztec/stdlib/avm';

/** Every injection this arm supports. Exported so a check enumerates them rather than typing them. */
export const INJECTIONS = [
  'revertCode',
  'teardownGas',
  'totalGas',
  'publicTxEffect',
  'returnValues',
  'revertReason',
  'publicInputs',
  'publicInputsPresence',
  'preState',
  'encoding',
  'tsResultMissing',
] as const;

export type Injection = (typeof INJECTIONS)[number];

const ENV = 'M19_INJECT_DIVERGENCE';

export function injection(): Injection | undefined {
  const name = process.env[ENV];
  if (!name) {
    return undefined;
  }
  if (!(INJECTIONS as readonly string[]).includes(name)) {
    // A misspelt injection must not read as "no injection": a control that silently does nothing
    // is a control that always passes.
    throw new Error(`${ENV}=${name} is not one of ${INJECTIONS.join(', ')}`);
  }
  return name as Injection;
}

/**
 * Perturb the wasm arm's RESULT for one of the result-field injections. Returns the result
 * unchanged for the injections that act elsewhere (`preState`, `encoding`).
 *
 * The perturbations are deliberately small and typed — a changed number, a dropped element, a
 * cleared field — rather than a replaced object, so that they exercise the comparison rather than
 * the plumbing around it.
 */
export function perturbResult(result: PublicTxResult, what: Injection | undefined): PublicTxResult {
  if (what === undefined) {
    return result;
  }
  const clone = Object.create(Object.getPrototypeOf(result), Object.getOwnPropertyDescriptors(result));
  switch (what) {
    case 'revertCode':
      clone.revertCode = { ...result.revertCode, equals: () => false, getCode: () => 99, isOK: () => false };
      return clone;
    case 'teardownGas':
      clone.gasUsed = { ...result.gasUsed, teardownGas: bump(result.gasUsed.teardownGas) };
      return clone;
    case 'totalGas':
      clone.gasUsed = { ...result.gasUsed, totalGas: bump(result.gasUsed.totalGas) };
      return clone;
    case 'publicTxEffect':
      clone.publicTxEffect = { ...result.publicTxEffect, equals: () => false };
      return clone;
    case 'returnValues':
      clone.getAppLogicReturnValues = () => result.getAppLogicReturnValues().slice(1);
      return clone;
    case 'revertReason':
      clone.findRevertReason = () => ({ originalMessage: 'injected', injected: true }) as any;
      return clone;
    case 'publicInputs':
      if (result.publicInputs !== undefined) {
        const bytes = Buffer.from(result.publicInputs.toBuffer());
        bytes[0] ^= 0xff;
        clone.publicInputs = { toBuffer: () => bytes };
      }
      return clone;
    case 'publicInputsPresence':
      clone.publicInputs = result.publicInputs === undefined ? { toBuffer: () => Buffer.alloc(32) } : undefined;
      return clone;
    default:
      return result;
  }
}

/** A `Gas` with one dimension moved by one, keeping `equals` honest. */
function bump(gas: any): any {
  const l2 = Number(gas.l2Gas) + 1;
  return {
    ...gas,
    l2Gas: l2,
    equals: (other: any) => Number(other?.l2Gas) === l2 && Number(other?.daGas) === Number(gas.daGas),
  };
}

/** The pre-state injection: a nullifier the native arm does not have. */
export function perturbPreState(insert: (n: Fr) => void, what: Injection | undefined): void {
  if (what === 'preState') {
    insert(new Fr(0xdeadbeefn));
  }
}

/**
 * The TypeScript-arm injection: pretend the interpreter produced nothing.
 *
 * Upstream's own harness treats an absent TS result as a reason to CONTINUE (it logs a warning and
 * runs the C++ side anyway, then asserts). The three-way arm must not inherit that for its own
 * comparison: a wasm-versus-TypeScript comparison that is silently skipped is a comparison whose
 * failure is never seen, which is the difference between a reference implementation and a
 * decoration. This injection is what proves the refusal is real.
 */
export function dropTsResult<T>(result: T | undefined, what: Injection | undefined): T | undefined {
  return what === 'tsResultMissing' ? undefined : result;
}

/** The encoding injection: one extra key beyond the declared patch delta. */
export function perturbEncodedConfig(what: Injection | undefined): Record<string, boolean> {
  return what === 'encoding' ? { injectedExtraConfigField: true } : {};
}
