// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart. The third arm.
//
// WHAT THIS IS. `avm.wasm` — Aztec's own C++ AVM compiled to wasm32-wasip1 — driven from inside
// the differential suite, against the SAME pre-transaction state the native C++ AVM and the
// TypeScript interpreter run from. It is the arm M19 exists to add: the other two have compared
// each other since upstream wrote `CppVsTsPublicTxSimulator`, and neither of them says anything
// about the artefact this runtime actually ships.
//
// THE STATE PROBLEM, AND WHY IT IS SOLVABLE RATHER THAN APPROXIMATED.
//
// The native arm reads a `NativeWorldStateService` fork through NAPI. The wasm arm cannot: M15
// chose the RESIDENT shape, so the module owns its own merkle DB and its own contract DB and
// nothing outside the module can hand it a fork. So "run the other side from the identical
// pre-transaction state" has to be established rather than assumed.
//
// Two measured facts make it exact rather than approximate, and both are asserted by the checks
// rather than trusted here:
//
//   1. `MemoryMerkleDB`'s genesis is byte-identical to `NativeWorldStateService.tmp()`'s, on all
//      four tree roots AND on all four `nextAvailableLeafIndex` values. (M14 established the
//      genesis prefill; M19 measured the equality from inside this suite.)
//   2. `BaseAvmSimulationTester` — upstream's own fixture, the one every apps-test builds its
//      world on — writes to the trees in EXACTLY TWO WAYS:
//        `sequentialInsert(MerkleTreeId.NULLIFIER_TREE,   [<32-byte nullifier>])`
//        `sequentialInsert(MerkleTreeId.PUBLIC_DATA_TREE, [PublicDataWrite.toBuffer()])`
//      and the reactor exports exactly the two matching entry points,
//      `avm_merkle_db_insert_indexed_leaves_nullifier_tree` and `…_public_data_tree`.
//
// So the mirror is total rather than best-effort: every pre-transaction tree write the fixture
// makes has a counterpart, and the equality of all four roots before every transaction is an
// ASSERTION rather than a comment. If upstream grows a third write kind — an unknown TREE ID
// inside a mirrored method, or one of the two mutating methods this mirror cannot replay
// (`batchInsert`, `updateArchive`) — `mirroringMerkleTree` REFUSES while the mirror is live rather
// than skipping it, and the root comparison would catch it a second time. Both halves of that
// sentence are load-bearing and only the first was true until the M19 review: see the note on
// `mirroringMerkleTree` for what was being forwarded silently.
//
// THE ENCODERS ARE UPSTREAM'S. `serializeWithMessagePack` from `@aztec/stdlib/avm` is what
// `CppPublicTxSimulator` itself calls; the only thing declared here is WHICH FIELD NAMES the C++
// structs carry, and those are quoted from the C++ side at the anchor rather than invented:
//
//   `avm_contract_db_register_class`    <- msgpack `ContractClassWithCommitment`
//        { id, artifactHash, privateFunctionsRoot, packedBytecode, publicBytecodeCommitment }
//   `avm_contract_db_register_instance` <- msgpack `[AztecAddress, ContractInstance]`
//        ContractInstance = { salt, deployer, currentContractClassId, originalContractClassId,
//                             initializationHash, immutablesHash, publicKeys }
//        PublicKeys       = { npkMHash, ivpkM, ovpkMHash, tpkMHash, mspkMHash, fbpkMHash }
//   `avm_merkle_db_insert_indexed_leaves_nullifier_tree`   <- msgpack `{ nullifier }`
//   `avm_merkle_db_insert_indexed_leaves_public_data_tree` <- msgpack `{ slot, value }`
//
// all from `barretenberg/cpp/src/barretenberg/vm2/common/aztec_types.hpp` and
// `crypto/merkle_tree/indexed_tree/indexed_leaf.hpp` at 233d8e0993, and from the M12/M13 reactor
// patches' own `args:` comments. `AvmContractClassHint` and `AvmContractInstanceHint` are the
// near-neighbours in `@aztec/stdlib/avm` and are deliberately NOT used: the class hint carries a
// `hintKey` and lacks `publicBytecodeCommitment`, so it is a different message, and encoding one
// where the other is expected would decode into plausible garbage rather than fail.
//
// CONTAINMENT. This file reaches `avm.wasm` and `@aztec-avm-runtime/node-host`. It does NOT reach
// `@aztec/native`, and nothing in `orchestration/` — the shipped package — imports it. It lives
// under `differential/` with the C++ arm for the same reason the C++ arm does: this directory is
// the one place a native or out-of-band AVM may be reached from.

import { Fr } from '@aztec/foundation/curves/bn254';
import { PublicDataWrite, deserializeFromMessagePack, serializeWithMessagePack } from '@aztec/stdlib/avm';
import { PublicTxResult } from '@aztec/stdlib/avm';
import type { AztecAddress } from '@aztec/stdlib/aztec-address';
import type { ContractClassPublic, ContractInstanceWithAddress } from '@aztec/stdlib/contract';
import { computePublicBytecodeCommitment } from '@aztec/stdlib/contract';
import type { MerkleTreeWriteOperations } from '@aztec/stdlib/interfaces/server';
import { MerkleTreeId } from '@aztec/stdlib/trees';

import { Reactor, compileAvm, instantiateAvm, unpack } from '../../../../../node-host/src/index.ts';

/**
 * A msgpack value's SHAPE — keys and leaf kinds, not values. Used only in diagnostics, and it
 * exists because the whole failure mode this arm has to survive is a field whose type moved.
 */
export function describeShape(value: unknown, depth = 0): string {
  if (value instanceof Uint8Array) {
    return `bin(${value.length})`;
  }
  if (Array.isArray(value)) {
    return depth > 4 ? `[${value.length}]` : `[${value.length}${value.length ? ': ' + describeShape(value[0], depth + 1) : ''}]`;
  }
  if (value !== null && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);
    if (depth > 4) {
      return `{${entries.map(([k]) => k).join(',')}}`;
    }
    return `{${entries.map(([k, v]) => `${k}:${describeShape(v, depth + 1)}`).join(', ')}}`;
  }
  return typeof value;
}

/** The four roots and their four leaf counts, as plain hex — the unit of the pre-state proof. */
export interface ResidentTreeRoots {
  l1ToL2MessageTree: { root: string; nextAvailableLeafIndex: number };
  noteHashTree: { root: string; nextAvailableLeafIndex: number };
  nullifierTree: { root: string; nextAvailableLeafIndex: number };
  publicDataTree: { root: string; nextAvailableLeafIndex: number };
}

const TREE_NAMES = ['l1ToL2MessageTree', 'noteHashTree', 'nullifierTree', 'publicDataTree'] as const;

/**
 * What the mirror does with a tree write the native arm makes.
 *
 * `apply` — replay it into the resident DB now. This is the fixture's SEEDING, before any
 *           transaction: the two arms must start from the same world, and the fixture only writes
 *           through this interface, so replaying is exact.
 * `off`   — drop it. This is what happens FOR THE DURATION OF A TRANSACTION, and the reason is not
 *           tidiness. During a transaction each arm must produce its own effects: replaying the
 *           native arm's into the resident DB would apply them on top of the wasm arm's own, and
 *           the module says so plainly (`Leaf is not updateable`). Dropping them is also what makes
 *           the post-transaction root comparison mean anything — two states that were copied from
 *           each other agree by construction.
 *
 * MEASURED, AND IT RULES OUT THE OBVIOUS ALTERNATIVE. Buffering the native arm's writes and
 * replaying them after the comparison — so the wasm arm could be reverted and re-synchronised —
 * DOES NOT WORK, and the reason is worth recording because it looks like it should. The native arm
 * reaches the world state through NAPI directly, so the tree writes it makes inside the AVM never
 * pass through `MerkleTreeWriteOperations` at all: replaying the 16 writes the mirror CAN see left
 * the nullifier tree at 135 leaves where the native arm had 193. The invisible ones are the
 * AVM's own padding inserts. So the wasm arm keeps its own writes, and the pre-state assertion
 * handles a carried divergence explicitly instead — see `ThreeWayPublicTxSimulator`.
 */
export type MirrorMode = 'apply' | 'off';

function hex32(v: unknown): string {
  if (v instanceof Uint8Array) {
    return Buffer.from(v).toString('hex');
  }
  if (v instanceof Fr) {
    return v.toBuffer().toString('hex');
  }
  throw new Error(`resident_avm: expected a 32-byte root, got ${typeof v}`);
}

/**
 * `StateReference` (what the native side answers with) rendered into the same shape the module
 * answers with, so the two are compared as data rather than through two different accessors.
 *
 * `StateReference` nests the three "partial" trees under `.partial`; the module's
 * `avm_merkle_db_get_tree_roots` flattens them. That difference is a JSON shape, not a
 * disagreement, and it is normalised HERE — once — rather than at each comparison site.
 */
export function nativeRootsOf(stateRef: any): ResidentTreeRoots {
  const partial = stateRef.partial ?? stateRef;
  const pick = (snapshot: any) => ({
    root: snapshot.root.toBuffer().toString('hex'),
    nextAvailableLeafIndex: Number(snapshot.nextAvailableLeafIndex),
  });
  return {
    l1ToL2MessageTree: pick(stateRef.l1ToL2MessageTree),
    noteHashTree: pick(partial.noteHashTree),
    nullifierTree: pick(partial.nullifierTree),
    publicDataTree: pick(partial.publicDataTree),
  };
}

/** The four-tree difference between two root sets, as a list of human-readable disagreements. */
export function rootDifferences(a: ResidentTreeRoots, b: ResidentTreeRoots): string[] {
  const out: string[] = [];
  for (const name of TREE_NAMES) {
    if (a[name].root !== b[name].root) {
      out.push(`${name}.root ${a[name].root} != ${b[name].root}`);
    }
    if (a[name].nextAvailableLeafIndex !== b[name].nextAvailableLeafIndex) {
      out.push(
        `${name}.nextAvailableLeafIndex ${a[name].nextAvailableLeafIndex} != ${b[name].nextAvailableLeafIndex}`,
      );
    }
  }
  return out;
}

/**
 * The wasm AVM with its two resident DBs, plus the seeding calls the fixture's world needs.
 *
 * One instance per tester. The module is compiled once per process and cached by `compileAvm`'s
 * caller; instantiation is ~0.4 s, measured.
 */
export class ResidentAvm {
  readonly reactor: Reactor;
  readonly contractDb: number;
  readonly merkleDb: number;
  /** Every class id already registered, so a repeated deployment is not double-registered. */
  private readonly classes = new Set<string>();
  private readonly instances = new Set<string>();
  /**
   * Whether the mirror is live.
   *
   * IT MUST NOT BE, DURING A TRANSACTION, and finding that out is what the first run of this arm
   * bought. The fixture's writes are SEEDING and must be replayed into the resident DB so both
   * arms start from the same world. The writes the SIMULATOR makes while running a transaction are
   * the arm's own output, and each arm produces them independently — the wasm arm inside the
   * module, the native arm into the fork. Replaying the native arm's into the resident DB would
   * apply the transaction's effects to the wasm side twice, and the module says so in the plainest
   * possible way: `avm_merkle_db_insert_indexed_leaves_nullifier_tree failed: Leaf is not
   * updateable`, because that nullifier is already there.
   *
   * So the comparator suspends the mirror around `simulate`, and the post-transaction root
   * comparison is then a real check that the two arms independently reached the same state rather
   * than a check that a copy is a copy.
   */
  private mirroring: MirrorMode = 'apply';

  get mirrorMode(): MirrorMode {
    return this.mirroring;
  }

  get isMirroring(): boolean {
    return this.mirroring === 'apply';
  }

  /** Run `body` with the mirror in `mode`. Restores the previous mode even if `body` throws. */
  async withMirrorMode<T>(mode: MirrorMode, body: () => Promise<T>): Promise<T> {
    const previous = this.mirroring;
    this.mirroring = mode;
    try {
      return await body();
    } finally {
      this.mirroring = previous;
    }
  }

  private constructor(reactor: Reactor, contractDb: number, merkleDb: number) {
    this.reactor = reactor;
    this.contractDb = contractDb;
    this.merkleDb = merkleDb;
  }

  static async open(wasmPath: string): Promise<ResidentAvm> {
    const reactor = await instantiateAvm(await compileAvm(wasmPath));
    return new ResidentAvm(reactor, reactor.createContractDb(), reactor.createMerkleDb());
  }

  close(): void {
    this.reactor.destroyContractDb(this.contractDb);
    this.reactor.destroyMerkleDb(this.merkleDb);
  }

  // -------------------------------------------------------------------------------------------
  // Seeding — the contract DB
  // -------------------------------------------------------------------------------------------

  /**
   * Register a contract class. `publicBytecodeCommitment` is not a field of `ContractClassPublic`,
   * so it is computed with upstream's own `computePublicBytecodeCommitment` — the same function
   * `PublicContractsDB` calls for the native arm, so the two arms cannot be seeded with different
   * commitments for the same bytecode.
   */
  async registerClass(contractClass: ContractClassPublic): Promise<void> {
    const key = contractClass.id.toString();
    if (this.classes.has(key)) {
      return;
    }
    this.classes.add(key);
    const publicBytecodeCommitment = await computePublicBytecodeCommitment(contractClass.packedBytecode);
    this.reactor.callWithBlob(
      'avm_contract_db_register_class',
      this.contractDb,
      serializeWithMessagePack({
        id: contractClass.id,
        artifactHash: contractClass.artifactHash,
        privateFunctionsRoot: contractClass.privateFunctionsRoot,
        packedBytecode: contractClass.packedBytecode,
        publicBytecodeCommitment,
      }),
    );
  }

  /** Register a contract instance under its address. The C++ side takes the pair as a tuple. */
  registerInstance(instance: ContractInstanceWithAddress): void {
    const key = instance.address.toString();
    if (this.instances.has(key)) {
      return;
    }
    this.instances.add(key);
    // The seven fields C++'s `ContractInstance` carries, and ONLY those. `ContractInstanceWith-
    // Address` additionally has `version` and `address`; `address` is the tuple's first element
    // and `version` has no C++ counterpart at all, so passing the object through would send a map
    // with two keys the far side has no field for. `publicKeys` IS passed through, because
    // upstream's `PublicKeys` already spells its six fields exactly as the C++ struct's msgpack
    // does — `npkMHash`, `ivpkM`, `ovpkMHash`, `tpkMHash`, `mspkMHash`, `fbpkMHash`.
    this.reactor.callWithBlob(
      'avm_contract_db_register_instance',
      this.contractDb,
      serializeWithMessagePack([
        instance.address,
        {
          salt: instance.salt,
          deployer: instance.deployer,
          currentContractClassId: instance.currentContractClassId,
          originalContractClassId: instance.originalContractClassId,
          initializationHash: instance.initializationHash,
          immutablesHash: instance.immutablesHash,
          publicKeys: instance.publicKeys,
        },
      ]),
    );
  }

  // -------------------------------------------------------------------------------------------
  // Seeding — the merkle DB
  // -------------------------------------------------------------------------------------------

  insertNullifier(nullifier: Fr): void {
    this.reactor.callWithBlob(
      'avm_merkle_db_insert_indexed_leaves_nullifier_tree',
      this.merkleDb,
      serializeWithMessagePack({ nullifier }),
    );
  }

  /** An append-only tree write: note hashes and L1→L2 messages. `[MerkleTreeId, vector<FF>]`. */
  appendLeaf(treeId: number, leaf: Fr): void {
    this.reactor.callWithBlob(
      'avm_merkle_db_append_leaves',
      this.merkleDb,
      serializeWithMessagePack([treeId, [leaf]]),
    );
  }

  insertPublicData(slot: Fr, value: Fr): void {
    this.reactor.callWithBlob(
      'avm_merkle_db_insert_indexed_leaves_public_data_tree',
      this.merkleDb,
      serializeWithMessagePack({ slot, value }),
    );
  }

  // -------------------------------------------------------------------------------------------
  // Checkpoints — both DBs, in lockstep (M13: two stacks moved by hand desynchronise silently)
  // -------------------------------------------------------------------------------------------

  createCheckpoint(): void {
    this.reactor.callWithHandle('avm_merkle_db_create_checkpoint', this.merkleDb);
    this.reactor.callWithHandle('avm_contract_db_create_checkpoint', this.contractDb);
  }

  commitCheckpoint(): void {
    this.reactor.callWithHandle('avm_contract_db_commit_checkpoint', this.contractDb);
    this.reactor.callWithHandle('avm_merkle_db_commit_checkpoint', this.merkleDb);
  }

  revertCheckpoint(): void {
    this.reactor.callWithHandle('avm_contract_db_revert_checkpoint', this.contractDb);
    this.reactor.callWithHandle('avm_merkle_db_revert_checkpoint', this.merkleDb);
  }

  // -------------------------------------------------------------------------------------------
  // Reading and running
  // -------------------------------------------------------------------------------------------

  treeRoots(): ResidentTreeRoots {
    const raw = this.reactor.callWithHandle('avm_merkle_db_get_tree_roots', this.merkleDb) as any;
    const pick = (s: any) => ({ root: hex32(s.root), nextAvailableLeafIndex: Number(s.nextAvailableLeafIndex) });
    return {
      l1ToL2MessageTree: pick(raw.l1ToL2MessageTree),
      noteHashTree: pick(raw.noteHashTree),
      nullifierTree: pick(raw.nullifierTree),
      publicDataTree: pick(raw.publicDataTree),
    };
  }

  /**
   * Run one transaction. The RAW result bytes are decoded with `deserializeFromMessagePack`, not
   * with node-host's decoder: M18 measured that the two are not interchangeable, because
   * `PublicTxResult.fromPlainObject` reaches `BaseField`, which takes a `Buffer` and refuses a
   * plain `Uint8Array`. Using the wrong one throws rather than producing a wrong answer, which is
   * the safe direction, but the right one is used here so the arm compares upstream's own type.
   */
  simulate(encodedInputs: Uint8Array): PublicTxResult {
    let outcome;
    try {
      outcome = this.reactor.simulate(encodedInputs, this.contractDb, this.merkleDb);
    } catch (e: any) {
      // THE EXPECTED FAILURE MODE OF THIS ARM IS SCHEMA DRIFT, and it arrives as `std::bad_cast`
      // from the module's msgpack reader with no field name in it. DD-12 says the oracle and the
      // module are pinned to lines two months apart, so a reader who sees `std::bad_cast` needs
      // the shape that was sent, not a stack trace. Printing it is the difference between
      // "something in the schema moved" and "`tx.hash` is a string here and a bin there".
      e.message = `${e.message}\n  encoded ${encodedInputs.length} B, shape: ${describeShape(unpack(encodedInputs))}`;
      throw e;
    }
    const bytes = this.reactor.result();
    if (bytes === null) {
      throw new Error('resident_avm: avm_simulate returned status 0 and no result bytes');
    }
    const decoded = PublicTxResult.fromPlainObject(deserializeFromMessagePack(Buffer.from(bytes)));
    if (decoded.revertCode.getCode() !== outcome.revertCode) {
      throw new Error(
        `resident_avm: the host read revertCode ${outcome.revertCode} and upstream's decoder read ` +
          `${decoded.revertCode.getCode()} from the same bytes`,
      );
    }
    return decoded;
  }
}

/**
 * A `MerkleTreeWriteOperations` that MIRRORS the fixture's pre-transaction tree writes into the
 * resident merkle DB, and forwards everything else untouched.
 *
 * Deliberately a Proxy over upstream's own object rather than a subclass: the interface has 20+
 * methods, upstream adds to it, and a subclass that forgot one would forward it by inheritance
 * while a hand-written wrapper would drop it.
 *
 * TOTAL OVER THE WRITE SURFACE, NOT OVER TWO METHOD NAMES. `MerkleTreeWriteOperations` declares
 * exactly four mutating methods — `sequentialInsert`, `appendLeaves`, `batchInsert` and
 * `updateArchive`. This mirror knows how to replay the first two, for the four tree ids the
 * fixtures use. The M19 review found that the other two were being forwarded SILENTLY, while this
 * comment and the milestone both said the mirror "throws on any tree write it has no counterpart
 * for": in fact only an unknown TREE ID inside a known METHOD threw, and an unknown METHOD went
 * through unnoticed. The pre-state root-and-leaf-count assertion would have caught the resulting
 * divergence on the next transaction, so it was a wrong claim rather than an open hole — but a
 * wrong claim about a load-bearing assertion is what this campaign keeps paying for.
 *
 * So every mutating method is named here, and one this mirror cannot replay REFUSES while the
 * mirror is live. It refuses only while live: inside `simulate` the mirror is 'off' by design and
 * the writes are the native simulator's own, which the wasm arm must not receive.
 */
const MUTATING_METHODS = ['sequentialInsert', 'appendLeaves', 'batchInsert', 'updateArchive'] as const;

export function mirroringMerkleTree(
  inner: MerkleTreeWriteOperations,
  resident: ResidentAvm,
): MerkleTreeWriteOperations {
  const mirrored = new Set<string>(['sequentialInsert', 'appendLeaves']);
  const unmirrored = new Set<string>(MUTATING_METHODS.filter(m => !mirrored.has(m)));
  return new Proxy(inner, {
    get(target, prop, receiver) {
      if (typeof prop !== 'string') {
        return Reflect.get(target, prop, receiver);
      }
      if (unmirrored.has(prop)) {
        return async (...args: unknown[]) => {
          if (resident.mirrorMode === 'apply') {
            throw new Error(
              `mirroringMerkleTree: ${prop} is a tree write this mirror has no counterpart for, and it ` +
                'was called while the mirror is live. The wasm arm would then run from a different state ' +
                'than the native arm. Add the mirror before adding the write.',
            );
          }
          return await (target as any)[prop](...args);
        };
      }
      if (!mirrored.has(prop)) {
        return Reflect.get(target, prop, receiver);
      }
      return async (treeId: MerkleTreeId, leaves: unknown[]) => {
        const result = await (target as any)[prop](treeId, leaves);
        const mode = resident.mirrorMode;
        if (mode === 'off') {
          return result;
        }
        for (const leaf of leaves) {
          applyOne(resident, prop, treeId, leaf);
        }
        return result;
      };
    },
  }) as MerkleTreeWriteOperations;
}

/** One mirrored write, named so the unmirrored case has one place to refuse from. */
function applyOne(resident: ResidentAvm, method: string, treeId: MerkleTreeId, leaf: unknown): void {
  const asFr = (v: unknown): Fr => (v instanceof Fr ? v : Fr.fromBuffer(v as Buffer));
  if (method === 'sequentialInsert') {
    if (treeId === MerkleTreeId.NULLIFIER_TREE) {
      resident.insertNullifier(asFr(leaf));
      return;
    }
    if (treeId === MerkleTreeId.PUBLIC_DATA_TREE) {
      const w = leaf instanceof PublicDataWrite ? leaf : PublicDataWrite.fromBuffer(leaf as Buffer);
      resident.insertPublicData(w.leafSlot, w.value);
      return;
    }
  } else if (method === 'appendLeaves') {
    if (treeId === MerkleTreeId.NOTE_HASH_TREE || treeId === MerkleTreeId.L1_TO_L2_MESSAGE_TREE) {
      resident.appendLeaf(treeId, asFr(leaf));
      return;
    }
  }
  throw new Error(
    `mirroringMerkleTree: ${method} into tree ${MerkleTreeId[treeId] ?? treeId}, which this mirror has no ` +
      'counterpart for. The wasm arm would then run from a different state than the native arm, and the ' +
      'root comparison would be the only thing standing between that and a silently weaker differential. ' +
      'Add the mirror before adding the write.',
  );
}

/** Every AztecAddress the fixture has deployed, for a seeding assertion that is not vacuous. */
export type SeededAddresses = ReadonlySet<AztecAddress>;
