// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart. THE THREE-WAY COMPARATOR.
//
// Upstream's `CppVsTsPublicTxSimulator` compares two implementations, neither of which is the one
// this runtime ships. This subclass adds the third — `avm.wasm` — and asserts on the SAME field
// list, in the same order, so that the wasm arm is held to the standard upstream already set
// rather than to a weaker one written here:
//
//   revert code | totalGas | publicGas | teardownGas | billedGas | the full public tx effect |
//   the AVM circuit public-inputs buffer, byte for byte | every app-logic return value |
//   the structured revert reason | the resulting tree roots
//
// THE CHECKPOINT DISCIPLINE, AND WHAT PROVES THE PRE-STATE IS IDENTICAL.
//
// Upstream's discipline for its own two arms is in the parent: the TypeScript interpreter runs
// inside a merkle-tree AND contracts-DB checkpoint, the checkpoint is reverted, and the C++ AVM
// then runs from the pre-transaction state. That is unchanged and is not reimplemented here.
//
// The wasm arm cannot share those checkpoints, because its trees and its contract DB are INSIDE
// the module (M15's resident shape). So it gets its own pair, taken and released in lockstep
// through `ResidentAvm` — M13 measured what happens when two such stacks are moved by hand: the
// contract DB unwound and the trees did not, no call returned an error, and no root was malformed.
//
// And because the two pre-states are held by different implementations, their identity is
// ASSERTED, not arranged. Before every transaction this class compares all four tree roots and all
// four `nextAvailableLeafIndex` values between the native fork and the resident DB. That assertion
// is the load-bearing one in the whole arm, and it can fail: the mirror in `resident_avm.ts`
// throws on any tree write it has no counterpart for, and a missed write would move exactly these
// numbers apart. After the transaction the same comparison runs again on the POST state, so the
// arm is pinned at both ends.
//
// WHAT IS COMPARED AGAINST WHAT. Three implementations give three pairs, and only two of them are
// independent — but the third is not therefore worthless, because a comparison that is skipped is
// a comparison whose failure is never seen. `wasm ↔ native-cpp` is the check that establishes the
// swap is safe; `wasm ↔ typescript-interpreter` keeps the TypeScript engine useful as a reference
// implementation and a second opinion. Both are asserted and both are counted, separately, and the
// count is per PAIR and per TRANSACTION so that neither number can be quoted as the other. That
// distinction is not pedantry: quoting a test count as a comparison count has overstated this
// corpus twice already (DRIFT.md D2, D7).

import { strict as assert } from 'assert';
import { createHash } from 'crypto';

import type { LoggerBindings } from '@aztec/foundation/log';
import { type PublicSimulatorConfig, PublicTxResult } from '@aztec/stdlib/avm';
import type { MerkleTreeWriteOperations } from '@aztec/stdlib/trees';
import type { GlobalVariables, Tx } from '@aztec/stdlib/tx';

import {
  encodeForPatchedModule,
  encodingDifferences,
  expectedPatchDifferences,
  residentWorldStateRevision,
} from './encode_inputs.ts';
import type { ExecutorMetricsInterface } from '../../executor_metrics_interface.js';
import type { PublicContractsDB } from '../../public_db_sources.js';
import { CppVsTsPublicTxSimulator } from '../cpp_vs_ts_public_tx_simulator.js';
import { recordDifferentialComparison } from '../differential_counters.js';
import type { MeasuredPublicTxSimulatorInterface } from '../public_tx_simulator_interface.js';
import { ResidentAvm, nativeRootsOf, rootDifferences } from './resident_avm.ts';
import { isRecordedDivergence, recordDivergences, surveying } from './divergence_ledger.ts';
import { dropTsResult, injection, perturbEncodedConfig, perturbPreState, perturbResult } from './fault_injection.ts';

/** The configuration names from `orchestration/src/simulator_selection.ts`, as counter labels. */
export const PAIR_WASM_VS_NATIVE_CPP = 'wasm-avm:native-cpp-avm';
export const PAIR_WASM_VS_TYPESCRIPT = 'wasm-avm:typescript-interpreter';
export const PAIR_TYPESCRIPT_VS_NATIVE_CPP = 'typescript-interpreter:native-cpp-avm';

/**
 * Every field the arms are held to, as data rather than as a run of `assert` lines.
 *
 * Written this way for one reason: a conjunction whose negative case exercises one conjunct is a
 * conjunction that passes when any of the others is dropped, and the campaign has already shipped
 * exactly that defect (a four-tree conjunction with one negative case). As a table, the mutation
 * harness can knock out any single field by name and see the arm go red for THAT field.
 */
export interface ComparedField {
  readonly name: string;
  /** Returns a description of the disagreement, or null when the two agree. */
  readonly differs: (a: PublicTxResult, b: PublicTxResult, config: PublicSimulatorConfig) => string | null;
}

const eq = (name: string, get: (r: PublicTxResult) => { equals: (o: any) => boolean }, show: (r: PublicTxResult) => string): ComparedField => ({
  name,
  differs: (a, b) => (get(a).equals(get(b) as any) ? null : `${name}: ${show(a)} != ${show(b)}`),
});

export const COMPARED_FIELDS: readonly ComparedField[] = [
  eq('revertCode', r => r.revertCode, r => String(r.revertCode.getCode())),
  eq('gasUsed.totalGas', r => r.gasUsed.totalGas, r => JSON.stringify(r.gasUsed.totalGas)),
  eq('gasUsed.publicGas', r => r.gasUsed.publicGas, r => JSON.stringify(r.gasUsed.publicGas)),
  eq('gasUsed.teardownGas', r => r.gasUsed.teardownGas, r => JSON.stringify(r.gasUsed.teardownGas)),
  eq('gasUsed.billedGas', r => r.gasUsed.billedGas, r => JSON.stringify(r.gasUsed.billedGas)),
  {
    // The detail carries a DIGEST of each side rather than a placeholder, and that is load-bearing
    // rather than cosmetic: the divergence ledger keys on the detail's signature, so a field whose
    // detail is a constant would let ANY disagreement in that field be excused by one recorded
    // entry. `<publicTxEffect>` was exactly such a constant, and the fault-injection controls
    // caught it — `M19_INJECT_DIVERGENCE=publicTxEffect` went GREEN.
    name: 'publicTxEffect',
    differs: (a, b) =>
      a.publicTxEffect.equals(b.publicTxEffect as any)
        ? null
        : `publicTxEffect: ${digestOf(a.publicTxEffect)} != ${digestOf(b.publicTxEffect)}`,
  },
  {
    // BYTE FOR BYTE, and only when both sides produced one.
    //
    // Split from the presence question deliberately. Upstream's own assertion is
    // `if (cppResult.publicInputs !== undefined) assert(...)`, i.e. it silently skips when the C++
    // side did not collect them — which most suites do not. Folding "one side has none" into this
    // field would mean the byte comparison could be satisfied by an absence, and the one field
    // whose deliverable says "byte for byte" is the last one that should be satisfiable that way.
    // So presence is its own field, below, and this one is a real buffer comparison whenever it
    // fires at all.
    name: 'publicInputs',
    differs: (a, b) => {
      if (a.publicInputs === undefined || b.publicInputs === undefined) {
        return null;
      }
      const x = a.publicInputs.toBuffer();
      const y = b.publicInputs.toBuffer();
      return x.equals(y) ? null : `publicInputs: ${x.length} B vs ${y.length} B, first differing byte ${firstDiff(x, y)}`;
    },
  },
  {
    // One side built the AVM circuit public inputs and the other did not. Reported, never folded
    // into the byte comparison. Measured cause where it fires: the TypeScript simulator builds them
    // unconditionally while the C++/wasm side honours `collectPublicInputs`.
    name: 'publicInputs.presence',
    differs: (a, b) =>
      (a.publicInputs === undefined) === (b.publicInputs === undefined)
        ? null
        : `publicInputs.presence: ${a.publicInputs !== undefined} vs ${b.publicInputs !== undefined}`,
  },
  {
    name: 'appLogicReturnValues',
    differs: (a, b, config) => {
      if (!config?.collectCallMetadata) {
        return null;
      }
      const x = a.getAppLogicReturnValues();
      const y = b.getAppLogicReturnValues();
      if (x.length !== y.length) {
        return `appLogicReturnValues: ${x.length} values vs ${y.length}`;
      }
      for (let i = 0; i < x.length; i++) {
        if (!x[i].equals(y[i])) {
          return `appLogicReturnValues[${i}] differs`;
        }
      }
      return null;
    },
  },
  {
    name: 'revertReason',
    differs: (a, b) => {
      const shape = (r: PublicTxResult) => {
        const reason = JSON.parse(JSON.stringify(r.findRevertReason() || {}));
        return JSON.stringify({ ...reason, originalMessage: undefined });
      };
      const x = shape(a);
      const y = shape(b);
      return x === y ? null : `revertReason: ${x} != ${y}`;
    },
  },
];

/** The tree names a `rootDifferences` list mentions. `noteHashTree.root …` -> `noteHashTree`. */
/** The ledger's key for one observed disagreement: a short hash of its detail text. */
export function signatureOf(detail: string): string {
  return createHash('sha256').update(detail).digest('hex').slice(0, 16);
}

export function treesDiffering(differences: readonly string[]): Set<string> {
  return new Set(differences.map(d => d.split('.')[0]));
}

function isSubset(a: ReadonlySet<string>, b: ReadonlySet<string>): boolean {
  return [...a].every(x => b.has(x));
}

/**
 * A short, stable digest of a value that has no readable rendering.
 *
 * `toBuffer()` where the type has one; otherwise a JSON projection. Either way it must MOVE when
 * the value moves, because the ledger's signature is computed from the text this produces.
 */
export function digestOf(value: any): string {
  let bytes: Buffer;
  try {
    bytes = typeof value?.toBuffer === 'function' ? Buffer.from(value.toBuffer()) : Buffer.from(JSON.stringify(value));
  } catch {
    bytes = Buffer.from(String(value));
  }
  return createHash('sha256').update(bytes).digest('hex').slice(0, 16);
}

function firstDiff(x: Buffer, y: Buffer): number {
  const n = Math.min(x.length, y.length);
  for (let i = 0; i < n; i++) {
    if (x[i] !== y[i]) {
      return i;
    }
  }
  return n;
}

/** One field on which two arms disagreed. */
export interface FieldDivergence {
  readonly field: string;
  readonly detail: string;
}

/** Compare two results across every field. Returns the disagreements; empty means they agree. */
export function compareResults(
  a: PublicTxResult,
  b: PublicTxResult,
  config: PublicSimulatorConfig,
): FieldDivergence[] {
  const out: FieldDivergence[] = [];
  for (const field of COMPARED_FIELDS) {
    const d = field.differs(a, b, config);
    if (d !== null) {
      out.push({ field: field.name, detail: d });
    }
  }
  return out;
}

/**
 * The three-way comparator. `wasm-avm`, `native-cpp-avm` and `typescript-interpreter`, one
 * transaction, one pre-state.
 */
export class ThreeWayPublicTxSimulator extends CppVsTsPublicTxSimulator {
  private readonly resident: ResidentAvm;
  /** Transactions this instance has compared, and the pairs it asserted on each. */
  private comparedTxs = 0;
  private comparedPairs = 0;
  /** Transactions whose two arms started from byte-identical trees. The pre-state proof, counted. */
  private identicalPreStates = 0;
  /**
   * Transactions on which the AVM circuit public-inputs buffer was actually compared byte for byte
   * — i.e. both arms built one. Counted rather than assumed, because with `collectPublicInputs`
   * false (the corpus default) the comparison does not fire at all, and a deliverable that says
   * "byte for byte" must be able to say how many times it happened.
   */
  private publicInputsCompared = 0;
  /** `pair field` for every divergence seen, so a survey can report the SET rather than a count. */
  private readonly observedFields = new Set<string>();
  /**
   * The trees that differed between the two arms when the previous transaction ended.
   *
   * A divergence the harness has already reported and attributed must not be re-reported as a
   * fresh failure of the next transaction. This carries it forward so the pre-state assertion can
   * demand EXACTLY it — no more and no less.
   */
  private carriedRootDiff: ReadonlySet<string> = new Set();

  constructor(
    merkleTree: MerkleTreeWriteOperations,
    contractsDB: PublicContractsDB,
    globalVariables: GlobalVariables,
    resident: ResidentAvm,
    config?: Partial<PublicSimulatorConfig>,
    bindings?: LoggerBindings,
  ) {
    super(merkleTree, contractsDB, globalVariables, config, bindings);
    this.resident = resident;
  }

  get transactionsCompared(): number {
    return this.comparedTxs;
  }

  get pairsCompared(): number {
    return this.comparedPairs;
  }

  /** How many transactions began with the two arms on byte-identical trees. */
  get preStatesProvedIdentical(): number {
    return this.identicalPreStates;
  }

  /** Every `pair field` this instance saw diverge. Empty is the claim the milestone wants. */
  get publicInputsBuffersCompared(): number {
    return this.publicInputsCompared;
  }

  get divergentFields(): string[] {
    return [...this.observedFields].sort();
  }

  public override async simulate(tx: Tx): Promise<PublicTxResult> {
    // THE MIRROR BUFFERS FOR THE WHOLE OF THIS METHOD. Everything the fixture wrote before now has
    // been replayed into the resident DB; everything written from here is a simulator's own output,
    // and each arm must produce it independently or the post-state comparison degrades into
    // checking that a copy is a copy. The buffer is what puts the two arms back in step afterwards
    // — see `MirrorMode` and step 5 below.
    return await this.resident.withMirrorMode('off', () => this.compareThreeWays(tx));
  }

  private async compareThreeWays(tx: Tx): Promise<PublicTxResult> {
    // ---- 1. The identical pre-transaction state, PROVED rather than arranged.
    const inject = injection();
    perturbPreState(n => this.resident.insertNullifier(n), inject);
    const preNative = nativeRootsOf(await this.merkleTree.getStateReference());
    const preWasm = this.resident.treeRoots();
    const preDiff = rootDifferences(preNative, preWasm);
    //
    // THE PRE-STATE ASSERTION, AND WHY IT IS NOT SIMPLY `preDiff.length === 0`.
    //
    // It IS that, for the first transaction of every fixture, and that is where the claim "both
    // arms started from the identical world" is established: genesis is byte-identical and the
    // mirror replayed every seeding write, so all four roots and all four leaf counts match.
    //
    // From the second transaction on, the honest statement is different, because D15 is REAL: on
    // 17 of 29 corpus transactions the two arms genuinely produce different tree roots, and the
    // wasm arm keeps its own. Demanding byte equality from then on would report the PREVIOUS
    // transaction's recorded divergence as a fresh failure of the current one — 15 red tests for
    // one cause, which is the shape the campaign already knows to distrust.
    //
    // So the assertion is exact and still capable of failing: the set of trees that differ going
    // IN must be a SUBSET of the set that differed coming OUT of the previous transaction. NOTHING
    // NEW may appear between transactions. For the first transaction the carried set is empty, so
    // this reduces to byte equality on all four trees and all four leaf counts — which is where the
    // identical-pre-state claim is actually established. `preStatesProvedIdentical` counts the
    // transactions where the difference was empty, and is reported rather than assumed.
    //
    // SUBSET AND NOT EQUALITY, and the reason is measured rather than a hedge. Demanding equality
    // failed on the token fixture with `entering [], carried [publicDataTree]`: the two arms had
    // CONVERGED. `BaseAvmSimulationTester.setFeePayerBalance` writes an ABSOLUTE value to the fee
    // payer's slot between transactions, and that slot is the one D15's gas difference had moved
    // apart, so replaying the fixture's write puts both arms back on the same leaf. A rule that
    // called that a failure would be asserting that a divergence must persist, which is not a
    // property anybody wants.
    const carried = this.carriedRootDiff;
    const entering = treesDiffering(preDiff);
    assert(
      surveying() || isSubset(entering, carried),
      'between transactions the two arms\' trees moved apart in a way no transaction accounts ' +
        `for: entering [${[...entering].sort().join(', ')}], carried from the previous ` +
        `transaction [${[...carried].sort().join(', ')}]`,
    );
    this.identicalPreStates += preDiff.length === 0 ? 1 : 0;

    // ---- 2. The wasm arm, inside its own checkpoint pair, BEFORE the native arm mutates the fork.
    const { upstream, patched } = encodeForPatchedModule(
      tx,
      this.globalVariables,
      this.config as PublicSimulatorConfig,
      residentWorldStateRevision(Number(this.globalVariables.blockNumber)),
      perturbEncodedConfig(inject),
    );
    // BOTH ARMS RECEIVED THE SAME TRANSACTION, and that is measured rather than asserted in prose.
    // `upstream` is byte-for-byte what `CppPublicTxSimulator` would hand the NAPI addon; `patched`
    // is the same thing plus the one field our own M9 observation-hook patch made required on the
    // wire (DRIFT.md D14). The delta is recomputed from the two encodings on every transaction, so
    // a second divergence appearing later is a failure here rather than an unnoticed widening.
    const encodingDelta = encodingDifferences(upstream, patched);
    const expectedDelta = expectedPatchDifferences();
    assert(
      JSON.stringify(encodingDelta) === JSON.stringify(expectedDelta),
      `the wasm arm's input differs from the native arm's by more than the declared patch delta: ` +
        `${JSON.stringify(encodingDelta)} vs the declared ${JSON.stringify(expectedDelta)}`,
    );
    const inputs = patched;
    this.resident.createCheckpoint();
    let wasmResult: PublicTxResult;
    let postWasm;
    try {
      wasmResult = perturbResult(this.resident.simulate(inputs), inject);
      postWasm = this.resident.treeRoots();
    } catch (e) {
      this.resident.revertCheckpoint();
      throw e;
    }

    // ---- 3. Upstream's own two arms, unchanged: TS in a checkpoint, reverted, then C++.
    let cppResult: PublicTxResult;
    try {
      cppResult = await super.simulate(tx);
    } catch (e) {
      this.resident.revertCheckpoint();
      throw e;
    }
    const tsResult = dropTsResult(this.lastTsResult, inject);

    let postDiff: string[] = [];
    try {
      // ---- 4. The comparisons. Both pairs, every field, and the post-state roots.
      const config = this.config as PublicSimulatorConfig;
      assert(
        tsResult !== undefined,
        'the TypeScript interpreter produced no result although the C++ AVM succeeded, so the ' +
          'wasm-versus-TypeScript comparison would be skipped rather than made',
      );
      if (wasmResult.publicInputs !== undefined && cppResult.publicInputs !== undefined) {
        this.publicInputsCompared++;
      }
      const postNative = nativeRootsOf(await this.merkleTree.getStateReference());
      postDiff = rootDifferences(postNative, postWasm);
      const found = [
        ...compareResults(wasmResult, cppResult, config).map(d => ({ pair: PAIR_WASM_VS_NATIVE_CPP, ...d })),
        ...compareResults(wasmResult, tsResult, config).map(d => ({ pair: PAIR_WASM_VS_TYPESCRIPT, ...d })),
        ...postDiff.map(d => ({ pair: PAIR_WASM_VS_NATIVE_CPP, field: 'treeRoots', detail: d })),
      ];
      this.comparedPairs += 2;
      recordDivergences(found.map(d => ({ ...d, signature: signatureOf(d.detail) })));
      const unaccounted = found.filter(d => !isRecordedDivergence(d.pair, d.field, signatureOf(d.detail)));
      assert(
        surveying() || unaccounted.length === 0,
        `the wasm AVM disagrees with an arm on a field no drift entry accounts for: ` +
          unaccounted.map(d => `${d.pair} ${d.field} — ${d.detail}`).join('; '),
      );
      for (const d of found) {
        this.observedFields.add(`${d.pair} ${d.field}`);
      }
    } catch (e) {
      this.resident.revertCheckpoint();
      throw e;
    }

    // ---- 5. The wasm arm KEEPS its own writes, and the divergence it carries is CARRIED, not
    // forgotten. See `carriedRootDiff`.
    this.resident.commitCheckpoint();
    this.carriedRootDiff = treesDiffering(postDiff);
    this.comparedTxs++;
    recordDifferentialComparison(true, [PAIR_WASM_VS_NATIVE_CPP, PAIR_WASM_VS_TYPESCRIPT], preDiff.length === 0);
    return cppResult;
  }
}

export class MeasuredThreeWayPublicTxSimulator
  extends ThreeWayPublicTxSimulator
  implements MeasuredPublicTxSimulatorInterface
{
  protected readonly metrics: ExecutorMetricsInterface;

  constructor(
    merkleTree: MerkleTreeWriteOperations,
    contractsDB: PublicContractsDB,
    globalVariables: GlobalVariables,
    metrics: ExecutorMetricsInterface,
    resident: ResidentAvm,
    config?: Partial<PublicSimulatorConfig>,
    bindings?: LoggerBindings,
  ) {
    super(merkleTree, contractsDB, globalVariables, resident, config, bindings);
    this.metrics = metrics;
  }

  public override async simulate(tx: Tx, txLabel: string = 'unlabeledTx'): Promise<PublicTxResult> {
    this.metrics.startRecordingTxSimulation(txLabel);
    let result: PublicTxResult | undefined;
    try {
      result = await super.simulate(tx);
    } finally {
      this.metrics.stopRecordingTxSimulation(txLabel, result?.gasUsed, result?.revertCode);
    }
    return result;
  }
}
