// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// ADDED HERE — this file has NO upstream counterpart.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   (none — added in this repo)
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260 (the surrounding tree's anchor)
//   licence:         Apache-2.0
//   local-edits:     three-way-differential
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

// ADDED HERE — no upstream counterpart.
//
// The wiring that lets an UNMODIFIED upstream apps-test build its world and have the wasm arm see
// the same one. Nothing in `public_tx_simulation_tester.ts`, `base_avm_simulation_tester.ts` or
// `simple_contract_data_source.ts` is edited: this file constructs upstream's own tester with two
// wrapped arguments, which is the seam upstream already provides (`PublicTxSimulationTester`'s
// constructor takes the `MerkleTreeWriteOperations` and the `SimpleContractDataSource`, and
// `create()` is only a convenience that builds both).
//
// That matters for more than tidiness. The whole claim of a differential is that the two sides ran
// the SAME thing; a fixture edited to accommodate one arm is a fixture that no longer proves it.

import type { GlobalVariables } from '@aztec/stdlib/tx';
import type { PublicSimulatorConfig } from '@aztec/stdlib/avm';
import type { ContractClassPublic, ContractInstanceWithAddress } from '@aztec/stdlib/contract';
import type { NativeWorldStateService } from '@aztec/world-state';

import { SimpleContractDataSource } from '../../fixtures/simple_contract_data_source.js';
import { PublicTxSimulationTester } from '../../fixtures/public_tx_simulation_tester.js';
import { TestExecutorMetrics } from '../../test_executor_metrics.js';
import { PublicContractsDB } from '../../public_db_sources.js';
import { ResidentAvm, mirroringMerkleTree } from './resident_avm.ts';
import { MeasuredThreeWayPublicTxSimulator } from './three_way_public_tx_simulator.ts';

/**
 * The compiled path of `avm.wasm`. Read from the environment because the module is a BUILD OUTPUT
 * (M6) and this repository does not check binaries in. There is no fallback and no default: a
 * missing variable throws with the command that produces the file, because a three-way harness
 * that silently degrades to two-way is precisely the decay this milestone exists to prevent.
 */
export function avmWasmPath(): string {
  const path = process.env.AVM_WASM_PATH;
  if (!path) {
    throw new Error(
      'AVM_WASM_PATH is not set, so the wasm arm cannot run and this suite would silently be a ' +
        'two-way differential. Build avm.wasm with `just avm-wasm-build` and point AVM_WASM_PATH ' +
        'at build-wasm-avm/bin/avm.wasm.',
    );
  }
  return path;
}

/**
 * A `SimpleContractDataSource` that also seeds the resident contract DB.
 *
 * Subclassed rather than proxied because there are exactly two mutation points and both are
 * upstream methods that `addNewContract` reaches through `this`, so overriding them catches every
 * path into the store. A Proxy would work too; the subclass is used because it type-checks.
 */
class MirroringContractDataSource extends SimpleContractDataSource {
  readonly resident: ResidentAvm;

  constructor(resident: ResidentAvm) {
    super();
    this.resident = resident;
  }

  override async addContractClass(contractClass: ContractClassPublic): Promise<void> {
    await super.addContractClass(contractClass);
    if (this.resident.isMirroring) {
      await this.resident.registerClass(contractClass);
    }
  }

  override async addContractInstance(contractInstance: ContractInstanceWithAddress): Promise<void> {
    await super.addContractInstance(contractInstance);
    if (this.resident.isMirroring) {
      this.resident.registerInstance(contractInstance);
    }
  }
}

export interface ThreeWayTester {
  readonly tester: PublicTxSimulationTester;
  readonly resident: ResidentAvm;
  readonly simulator: MeasuredThreeWayPublicTxSimulator;
  close(): void;
}

/**
 * Build upstream's tester with all three arms attached.
 *
 * `config` defaults to the caller's, unchanged: the three-way arm does not need a different
 * configuration from the two-way one, and needing one would be evidence that the arms are not
 * comparable.
 */
export async function createThreeWayTester(
  worldStateService: NativeWorldStateService,
  globals: GlobalVariables,
  config: PublicSimulatorConfig,
  metrics: TestExecutorMetrics = new TestExecutorMetrics(),
  wasmPath: string = avmWasmPath(),
): Promise<ThreeWayTester> {
  const resident = await ResidentAvm.open(wasmPath);
  const fork = await worldStateService.fork();
  const merkleTree = mirroringMerkleTree(fork, resident);
  const contractDataSource = new MirroringContractDataSource(resident);

  let simulator: MeasuredThreeWayPublicTxSimulator | undefined;
  const tester = new PublicTxSimulationTester(
    merkleTree,
    contractDataSource,
    globals,
    metrics,
    (mt, cdb, g, m, c) => {
      simulator = new MeasuredThreeWayPublicTxSimulator(mt, cdb as PublicContractsDB, g, m, resident, c);
      return simulator;
    },
    config,
  );
  if (simulator === undefined) {
    throw new Error('createThreeWayTester: upstream tester did not call the simulator factory');
  }
  return { tester, resident, simulator, close: () => resident.close() };
}
