#!/usr/bin/env python3
"""Render CARRY-LEDGER.md from the machine-readable sources.

The ledger is generated, not written. Three inputs:

  carry/series.json     status, URL, reason, maintenance consequence, dependency
                        structure — the authority for all of it
  carry/exposure.json   what the whole set costs if nothing is accepted, from
                        tools/measure_carry_exposure.py
  carry/rebase.json     the last recorded replay onto upstream, from
                        tools/rebase_upstream_patches.py --json (optional)

Generating it is the point. A ledger maintained by hand beside a JSON file is two
documents that drift, and this project has already paid for that twice; here the
prose cannot disagree with the data because it is produced from it.

The rendering is a PURE FUNCTION OF THE THREE INPUT FILES. It carries no wall
clock, and that is a correction rather than an omission: an earlier version wrote
`Generated <date.today()>` into the output, which made the committed ledger a
function of the calendar as well as of the data. `verify_carry_ledger_complete`
compares the committed file to what the data renders to, so from the day after
each regeneration that check failed for a reason that said nothing about the
ledger — and, because it rendered over the tracked file to do the comparison, it
left the working tree dirty on its way out. Every date the ledger states now comes
from the data (upstream commit dates in `exposure.json`, the replayed tip in
`rebase.json`); when it was generated is git's question and git answers it exactly.

Reading the inputs from elsewhere and writing the output elsewhere are both
supported (`--series`, `--exposure`, `--rebase`, `--output`) so a check can render
into a temporary directory and compare, without ever writing a tracked file.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SERIES = REPO_ROOT / "carry" / "series.json"
EXPOSURE = REPO_ROOT / "carry" / "exposure.json"
REBASE = REPO_ROOT / "carry" / "rebase.json"
OVERLAP = REPO_ROOT / "carry" / "overlap.json"
OUT = REPO_ROOT / "CARRY-LEDGER.md"

STATUS_MEANING = {
    "prepared": "ready to file; **not filed**",
    "submitted": "filed upstream; awaiting a verdict",
    "accepted": "merged upstream",
    "declined": "upstream said no; carried downstream",
    "stalled": "filed, no verdict, trail gone cold; carried downstream",
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--series", type=Path, default=SERIES)
    ap.add_argument("--exposure", type=Path, default=EXPOSURE)
    ap.add_argument("--rebase", type=Path, default=REBASE)
    ap.add_argument("--overlap", type=Path, default=OVERLAP)
    ap.add_argument("--output", type=Path, default=OUT,
                    help="where to write; '-' writes to stdout")
    args = ap.parse_args(argv)

    series = json.loads(args.series.read_text())
    exposure = json.loads(args.exposure.read_text()) if args.exposure.is_file() else None
    rebase = json.loads(args.rebase.read_text()) if args.rebase.is_file() else None
    overlap = json.loads(args.overlap.read_text()) if args.overlap.is_file() else None
    patches = sorted(series["patches"], key=lambda p: p["order"])

    L: list[str] = []
    w = L.append

    w("# Carry ledger — the `aztec-packages` patch series")
    w("")
    w("<!-- GENERATED by tools/render_carry_ledger.py. Do not edit by hand: edit")
    w("     carry/series.json and re-run `just carry-ledger`. -->")
    w("")
    w("Where each prepared patch stands with upstream, what it costs us to carry, and what")
    w("the whole set costs if upstream accepts none of it.")
    w("")
    w("Every patch here is traceable to a directory under")
    w("`codetracer-specs/upstream-bugs/`, which holds the patch itself, the `PR.md` written")
    w("for an upstream audience, and a verification script with a meaningful exit status.")
    w("")
    w("Generated from `carry/series.json`, `carry/exposure.json` and `carry/rebase.json` by")
    w("`tools/render_carry_ledger.py`. The rendering is a function of those files alone and of")
    w("no wall clock, so re-rendering an unchanged set of inputs reproduces this file byte for")
    w("byte on any day. When it was last regenerated is git's question.")
    w("")

    w("## Status")
    w("")
    w("| # | Patch | Entry | Status | Upstream |")
    w("| --- | --- | --- | --- | --- |")
    for p in patches:
        led = p["ledger"]
        url = led["url"] or "—"
        w("| %d | `%s` | `%s` | **%s** | %s |"
          % (p["order"], p["title"], p["entry"], led["status"], url))
    w("")
    counts: dict[str, int] = {}
    for p in patches:
        counts[p["ledger"]["status"]] = counts.get(p["ledger"]["status"], 0) + 1
    w("%d patch(es): %s."
      % (len(patches), ", ".join("%d %s" % (v, k) for k, v in sorted(counts.items()))))
    w("")
    for k in sorted(counts):
        w("* **%s** — %s." % (k, STATUS_MEANING[k]))
    w("")
    if counts.get("prepared"):
        w("> **Nothing has been filed.** Filing is a manual step: each patch has a")
        w("> submission script under `submit/` that a human runs. See \"Filing\" below.")
        w("")

    w("## Order and dependencies")
    w("")
    w("| # | Branch on our fork | Applies without | Builds without | Standalone |")
    w("| --- | --- | --- | --- | --- |")
    for p in patches:
        ad = ", ".join(p["apply_depends_on"]) or "anything"
        bd = ", ".join(p["build_depends_on"]) or "anything"
        w("| %d | `%s` | %s | %s | %s |"
          % (p["order"], p["branch"], ad, bd, "yes" if p["standalone"] else "**no**"))
    w("")
    w("`applies without` names APPLY prerequisites — patches without which `git am` is")
    w("rejected. `builds without` names BUILD prerequisites — patches without which the tree")
    w("applies cleanly and then fails to compile. The two are different claims and were")
    w("established separately, by trying each combination rather than by grouping them.")
    w("")

    w("## Per patch")
    w("")
    for p in patches:
        led = p["ledger"]
        w("### %d. `%s`" % (p["order"], p["title"]))
        w("")
        w("* **Entry**: `codetracer-specs/upstream-bugs/%s/`" % p["entry"])
        w("* **Branch**: `%s` on `metacraft-labs/aztec-packages`" % p["branch"])
        w("* **Kind**: %s" % p["kind"])
        w("* **Status**: **%s** — %s" % (led["status"], STATUS_MEANING[led["status"]]))
        if led["url"]:
            w("* **Upstream**: %s" % led["url"])
        if led["reason"]:
            w("* **Reason given**: %s" % led["reason"])
        if led["maintenance"]:
            w("* **Maintenance consequence**: %s" % led["maintenance"])
        if led["status"] == "declined" and not (led["reason"] and led["maintenance"]):
            w("* **INCOMPLETE LEDGER ENTRY**: a declined patch must record both a reason and")
            w("  a maintenance consequence.")
        w("* **Submission script**: `%s`" % led["submission_script"])
        w("")
        if p.get("carry_note"):
            w(p["carry_note"])
            w("")
        if exposure:
            row = next((r for r in exposure["per_patch"] if r["id"] == p["id"]), None)
            if row:
                kinds = ", ".join("%d %s" % (v, k) for k, v in sorted(row["kinds"].items()))
                w("Size: **%d file(s), +%d / −%d over %d hunk(s)** (%s)."
                  % (row["files"], row["added"], row["removed"], row["hunks"], kinds))
                w("")

    w("## Total exposure if nothing is accepted")
    w("")
    if not exposure:
        w("**NOT MEASURED.** Run `just carry-exposure`.")
        w("")
    else:
        cat_f = exposure["by_category_files"]
        cat_l = exposure["by_category_lines"]
        w("Measured against `%s` (%s) with `tools/measure_carry_exposure.py`, not estimated."
          % (exposure["base"][:10], exposure["base_date"]))
        w("")
        w("**Size.** %d distinct files, +%d / −%d. That is git's own diff between the base"
          % (exposure["files_total"], exposure["union_added"], exposure["union_removed"]))
        w("and the base with all five patches applied — what the SET costs — and it is not the")
        w("same arithmetic as summing the five per-patch rows, which gives +%d / −%d over %d"
          % (exposure["sum_of_per_patch_added"], exposure["sum_of_per_patch_removed"],
             exposure["sum_of_per_patch_hunks"]))
        w("hunks. The two differ because %d file(s) are touched by more than one patch and one"
          % (sum(r["files"] for r in exposure["per_patch"]) - exposure["files_total"]))
        w("patch's added line can be another's context. Both are stated so neither can be quoted")
        w("as the other. The %d hunks are a property of the patch files, not of the endpoint diff."
          % exposure["patch_hunks"])
        w("")
        w("| Category | Files | Changed lines |")
        w("| --- | --- | --- |")
        for c in sorted(cat_f):
            w("| %s | %d | %d |" % (c, cat_f[c], cat_l.get(c, 0)))
        w("")
        w("**Conflict surface.** %d file(s) are created by the series, %d renamed and %d"
          % (exposure["files_created"], exposure["files_renamed"], exposure["files_deleted"]))
        w("deleted; those cost nothing to rebase, because upstream has no version of them to")
        w("move underneath us. **%d files are modified**, and those are the whole conflict"
          % exposure["files_modified"])
        w("surface.")
        w("")
        w("**Churn.** Over the twelve months before the base (`%s` .. `%s`), upstream made"
          % (exposure["churn_window"][0], exposure["churn_window"][1]))
        w("**%.2f commits per month** touching a file this series modifies, and"
          % exposure["upstream_commits_per_month_touching_a_modified_file"])
        w("**%.2f per month** touching the LINES it modifies. The second number is the one"
          % exposure["upstream_commits_per_month_touching_a_carried_hunk"])
        w("that predicts a rebase conflict; the first is an upper bound on it.")
        w("")
        line_churn = exposure.get("line_churn_12mo_before_base", {})
        hot = sorted(line_churn.items(), key=lambda kv: -kv[1])[:8]
        if hot:
            w("The eight files whose carried lines upstream touched most, in that window:")
            w("")
            w("| Commits on the carried lines | File |")
            w("| --- | --- |")
            for path, n in hot:
                w("| %d | `%s` |" % (n, path))
            w("")
        w("**Against the spike's estimate.** The spike said \"roughly 80 lines of CMake plus")
        w("one function-level rebase risk in `hybrid_execution.cpp`\". Measured, the CMake")
        w("side is **%d files and %d changed lines**, not 80; and `hybrid_execution.cpp` is"
          % (cat_f.get("cmake", 0), cat_l.get("cmake", 0)))
        hy = "barretenberg/cpp/src/barretenberg/vm2/simulation/standalone/hybrid_execution.cpp"
        sh = "barretenberg/cpp/src/barretenberg/vm2/simulation_helper.cpp"
        if hy in line_churn and sh in line_churn:
            w("**not** the top rebase risk: %d upstream commits landed on its carried lines in"
              % line_churn[hy])
            w("twelve months, against %d for `simulation_helper.cpp`. The estimate named the"
              % line_churn[sh])
            w("wrong file and understated the CMake side.")
        w("")

    w("## Rebase harness")
    w("")
    w("`just rebase-upstream-patches` fetches upstream and replays the set onto its tip,")
    w("reporting per patch whether it applies, is already present, or conflicts — and on")
    w("which files. It exits non-zero if any patch we still carry stops applying. CI runs it")
    w("weekly and on every change to the series, so the cost is a dated failure rather than")
    w("a discovery during an emergency.")
    w("")
    if rebase:
        w("Last recorded replay, onto `%s` (%s), %d commit(s) past the base:"
          % (rebase["tip_ref"], rebase["tip"][:10], rebase["commits_since_base"]))
        w("")
        w("| Patch | Result |")
        w("| --- | --- |")
        for row in rebase["patches"]:
            extra = ""
            if row.get("paths"):
                extra = " on " + ", ".join("`%s`" % x for x in row["paths"])
            if row.get("blocked_by"):
                extra = " by " + ", ".join(row["blocked_by"])
            w("| `%s` | %s%s |" % (row["id"], row["result"], extra))
        w("")
    else:
        w("**No replay recorded yet.** Run `just rebase-upstream-patches`.")
        w("")

    w("### Overlap with upstream's own changes")
    w("")
    w("Applying is one question and BUILDING is another. M6 and M10 build the AVM_WASM tree")
    w("and run upstream's own native suites from the base plus this stack, and that evidence")
    w("describes the REBASED tree only under an argument. The argument used to be that")
    w("upstream had touched no path this series modifies. It has, so the argument is now")
    w("three conjuncts, checked by `verify_carry_set_applies_to_upstream_head`: upstream has")
    w("changed nothing under `barretenberg/cpp`, which is what both builds compile; every")
    w("overlap outside that tree is acknowledged below; and the two sets of changed lines are")
    w("disjoint per file. An overlap INSIDE `barretenberg/cpp` cannot be acknowledged at all.")
    w("")
    if overlap is None:
        w("**No acknowledgement file.** `carry/overlap.json` is missing.")
        w("")
    elif not overlap.get("acknowledged"):
        w("No path upstream has changed since the base is a path this series modifies.")
        w("")
    else:
        ranges = (exposure or {}).get("union_pre_ranges", {})
        w("| Path | Patch | Upstream changes | This series changes | Acknowledged at |")
        w("| --- | --- | --- | --- | --- |")
        for path, e in sorted(overlap["acknowledged"].items()):
            ours = ", ".join("%d-%d" % (a, b) for a, b in ranges.get(path, [])) or "n/a"
            # DATA FIRST, PROSE ONLY AS A FALLBACK. This column used to be scraped out of the
            # entry's `reason` with a regex for the phrase `at base lines N..M`, so an entry whose
            # reason was true but worded differently rendered as `see below` — two of the three did,
            # the moment a second overlap was acknowledged. `upstream_ranges` carries the region as
            # data, and `verify_carry_set_applies_to_upstream_head` asserts it equals the range the
            # decision procedure computes, so it cannot drift from the measurement.
            declared = e.get("upstream_ranges")
            if declared:
                theirs = ", ".join("%d-%d" % (a, b) for a, b in declared)
            else:
                m = re.search(r"at base lines ([0-9]+\.\.[0-9]+)", e.get("reason", ""))
                theirs = m.group(1).replace("..", "-") if m else "see below"
            w("| `%s` | %s | lines %s | lines %s | `%s` |"
              % (path, ", ".join(e.get("patch", [])), theirs, ours,
                 (e.get("acknowledged_at_tip") or "")[:10]))
        w("")
        for path, e in sorted(overlap["acknowledged"].items()):
            w("**`%s`** — %s" % (path, e.get("reason", "")))
            w("")
            w("*Why it does not reach the build.* %s" % e.get("why_it_does_not_reach_the_build", ""))
            w("")
            w("*If it stops holding.* %s" % e.get("consequence_if_it_stops_holding", ""))
            w("")

    w("## Filing")
    w("")
    w("Nothing in this repository files anything upstream, and no automation may. Each")
    w("patch has one script; a human runs it:")
    w("")
    for p in patches:
        w("    %s" % p["ledger"]["submission_script"])
    w("")
    w("Each one checks that its branch still rebuilds byte for byte from its patch file,")
    w("runs the tracker search the entry requires (and stops if the search cannot run),")
    w("refuses to open a second pull request for a branch that already has one, and records")
    w("the URL back into `carry/series.json`, the entry's `PR.md` and this ledger. Add")
    w("`--dry-run` to see exactly what would be sent without sending it.")
    w("")
    w("The fifth refuses to run until the first three have been filed, because it stacks on")
    w("them and its body names their pull request numbers.")
    w("")

    text = "\n".join(L) + "\n"
    if str(args.output) == "-":
        sys.stdout.write(text)
    else:
        args.output.write_text(text)
        print("wrote %s (%d lines)" % (args.output, len(L) + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
