#!/usr/bin/env python3
"""THE HEADLINE. The number of differential COMPARISONS, and a floor it may not fall below.

M19's deliverable, in one sentence: CI must report the comparison count as its headline figure so
that a test count can never stand in for it again.

The history that makes this necessary is in DRIFT.md D2 and D7 and in `fixtures/CORPUS.md`. The
suite reports 758 passing tests. 77 of them carry the `(TS Simulator)` label, which selects the
DIFFERENTIAL harness — upstream's names for its two arms mean the opposite of what they look like.
Those 77 tests drive 74 transactions through two implementations. "756 differential tests" was
quoted; the number was 74. An order of magnitude, from reading one label.

So this tool prints, in order of decreasing honesty:

  1. TRANSACTIONS COMPARED — the unit. One transaction run through two or three implementations
     from one pre-transaction state, with every asserted field agreeing or accounted for.
  2. IMPLEMENTATION-PAIR COMPARISONS — how many (A, B) assertions that came to. Three-way
     transactions contribute three; two-way ones contribute one. Reported beside the first and
     never instead of it.
  3. Tests. Last, smallest in the output, and labelled as what it is not.

It reads only MEASURED fixtures — `differential-arm-counts.json` and `three-way-arm-counts.json`,
both regenerated by their own tools — so the headline cannot drift from the measurement without
one of those tools being run and disagreeing.

Usage:
    tools/report_comparisons.py [--floor FILE] [--json FILE]

Exit 0 at or above the floor, 3 below it, 2 if a fixture is missing (a measurement that is absent
is not a measurement of zero).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ARM_COUNTS = REPO / "fixtures" / "differential-arm-counts.json"
THREE_WAY = REPO / "fixtures" / "three-way-arm-counts.json"
FLOOR = REPO / "fixtures" / "differential-comparison-floor.json"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--floor", default=str(FLOOR))
    ap.add_argument("--json", default="")
    args = ap.parse_args()

    for path in (ARM_COUNTS, THREE_WAY, Path(args.floor)):
        if not path.exists():
            sys.stderr.write(
                f"report_comparisons: {path} is missing. The headline is read from measured\n"
                "  fixtures and there is no fallback: a missing measurement must not be reported\n"
                "  as a measurement of zero.\n"
                "  Remedy: tools/measure_differential.py and AVM_WASM_PATH=… tools/measure_three_way.py\n"
            )
            return 2

    two_way = json.loads(ARM_COUNTS.read_text())
    three_way = json.loads(THREE_WAY.read_text())
    floor = json.loads(Path(args.floor).read_text())

    arms = [
        {
            "arm": "two-way default suite (typescript-interpreter vs native-cpp-avm)",
            "transactions": two_way["defaultSuite"]["comparisons"],
            "pairs": two_way["defaultSuite"]["comparisons"],
            "tests": two_way["defaultSuite"]["testCounts"]["totalPassed"],
        },
        {
            "arm": "two-way opcode-spam arm (typescript-interpreter vs native-cpp-avm)",
            "transactions": two_way["opcodeSpamArm"]["comparisons"],
            "pairs": two_way["opcodeSpamArm"]["comparisons"],
            "tests": two_way["opcodeSpamArm"]["testCounts"]["totalPassed"],
        },
        {
            "arm": "three-way arm (wasm-avm vs native-cpp-avm vs typescript-interpreter)",
            "transactions": three_way["transactionsCompared"],
            "pairs": three_way["pairsCompared"],
            "tests": three_way["testCounts"]["totalPassed"],
        },
    ]
    total_tx = sum(a["transactions"] for a in arms)
    total_pairs = sum(a["pairs"] for a in arms)
    total_tests = sum(a["tests"] for a in arms)

    print("=== DIFFERENTIAL COMPARISONS ===")
    print(f"  TRANSACTIONS COMPARED           {total_tx}")
    print(f"  implementation-pair comparisons {total_pairs}")
    print("  per arm:")
    for a in arms:
        print(f"    {a['transactions']:>5}  tx  {a['pairs']:>5}  pairs   {a['arm']}")
    print(f"  wasm arm ran from byte-identical pre-state on {three_way['preStatesProvedIdentical']} transactions")
    print(f"  (tests: {total_tests} — NOT the comparison count; see DRIFT.md D2 and D7)")
    print(f"  floor: {floor['transactions']} transactions / {floor['pairs']} pairs")

    report = {
        "generator": "tools/report_comparisons.py",
        "transactionsCompared": total_tx,
        "pairsCompared": total_pairs,
        "testsPassed": total_tests,
        "arms": arms,
        "floor": floor,
        "belowFloor": total_tx < floor["transactions"] or total_pairs < floor["pairs"],
    }
    if args.json:
        Path(args.json).write_text(json.dumps(report, indent=2) + "\n")

    if report["belowFloor"]:
        sys.stderr.write(
            f"report_comparisons: the differential surface SHRANK — {total_tx} transactions / "
            f"{total_pairs} pairs against a floor of {floor['transactions']} / {floor['pairs']}.\n"
            "  Coverage that falls silently is the failure this floor exists to prevent. Either\n"
            "  restore it, or lower the floor deliberately and say why in the commit message.\n"
        )
        return 3
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
