// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/private/factory.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

import { type Logger, type LoggerBindings, resolveLogger } from '@aztec/foundation/log';

import { promises as fs } from 'fs';

import { NativeACVMSimulator } from './acvm_native.js';
import { WASMSimulator } from './acvm_wasm.js';
import type { CircuitSimulator } from './circuit_simulator.js';

export type SimulatorConfig = {
  acvmBinaryPath?: string;
  acvmWorkingDirectory?: string;
};

export function getSimulatorConfigFromEnv() {
  const { ACVM_BINARY_PATH, ACVM_WORKING_DIRECTORY } = process.env;
  return {
    acvmWorkingDirectory: ACVM_WORKING_DIRECTORY ? ACVM_WORKING_DIRECTORY : undefined,
    acvmBinaryPath: ACVM_BINARY_PATH ? ACVM_BINARY_PATH : undefined,
  };
}

export async function createSimulator(
  config: SimulatorConfig,
  loggerOrBindings?: Logger | LoggerBindings,
): Promise<CircuitSimulator> {
  const logger = resolveLogger('simulator', loggerOrBindings);
  if (config.acvmBinaryPath && config.acvmWorkingDirectory) {
    try {
      await fs.access(config.acvmBinaryPath, fs.constants.R_OK);
      await fs.mkdir(config.acvmWorkingDirectory, { recursive: true });
      logger.info(`Using native ACVM at ${config.acvmBinaryPath} and working directory ${config.acvmWorkingDirectory}`);
      const acvmLogger = logger.createChild('acvm-native');
      return new NativeACVMSimulator(config.acvmWorkingDirectory, config.acvmBinaryPath, undefined, acvmLogger);
    } catch {
      logger.warn(`Failed to access ACVM at ${config.acvmBinaryPath}, falling back to WASM`);
    }
  }
  logger.info('Using WASM ACVM simulation');
  const wasmLogger = logger.createChild('wasm');
  return new WASMSimulator(wasmLogger);
}
