// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/public/avm/avm_simulator_interface.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

/**
 * Interface for AvmSimulator to break the circular dependency between avm_context.ts and avm_simulator.ts
 */
export interface AvmSimulatorInterface {
  execute(): Promise<any>; // Using any here to avoid importing AvmContractCallResult
  executeBytecode(bytecode: Buffer): Promise<any>;
  getBytecode(): Buffer | undefined;
}
