// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/server.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     none
//   inventory:       REUSE-INVENTORY.md RI-25
// END VENDORED-PROVENANCE

export * from './public/index.js';
export * from './private/acvm/index.js';
export { WASMSimulatorWithBlobs } from './private/acvm_wasm_with_blobs.js';
export { NativeACVMSimulator } from './private/acvm_native.js';
export { SimulatorRecorderWrapper } from './private/circuit_recording/simulator_recorder_wrapper.js';
export { MemoryCircuitRecorder } from './private/circuit_recording/memory_circuit_recorder.js';
export { type CircuitSimulator, type DecodedError } from './private/circuit_simulator.js';
export * from './common/index.js';
