// BEGIN VENDORED-PROVENANCE — generated by `just vendor-headers` (tools/provenance.py); do not hand-edit.
// VENDORED — not our code. Re-vendor rather than editing here.
//   upstream-repo:   AztecProtocol/aztec-packages
//   upstream-path:   yarn-project/simulator/src/testing.ts
//   upstream-commit: 3a68d68ac29aaf04fc6251c80a8eb874043cb260
//   licence:         Apache-2.0
//   local-edits:     derived
//   inventory:       REUSE-INVENTORY.md RI-24
// END VENDORED-PROVENANCE

export { FileCircuitRecorder } from './private/circuit_recording/file_circuit_recorder.js';
